export interface DialogueLine {
  speaker: 'A' | 'B'
  dutch: string
  english: string
}

export interface Expression {
  dutch: string
  english: string
  note: string
}

export interface RealConversation {
  id: string
  title: string
  dutchTitle: string
  emoji: string
  description: string
  level: 'A1' | 'A2' | 'B1'
  context: string
  speakers: { A: string; B: string }
  lines: DialogueLine[]
  expressions: Expression[]
}

export const realConversations: RealConversation[] = [
  {
    id: 'koffie-werk',
    title: 'Coffee at Work',
    dutchTitle: 'Koffie op het werk',
    emoji: '☕',
    description: 'Two colleagues bonding over bad coffee and worse news',
    level: 'A2',
    context: 'Maandagochtend. Lars staat al vijf minuten naar de koffieautomaat te staren. Noor komt erbij.',
    speakers: { A: 'Lars', B: 'Noor' },
    lines: [
      { speaker: 'A', dutch: 'Hé Noor. Koffie?', english: 'Hey Noor. Coffee?' },
      { speaker: 'B', dutch: 'Alsof ik zonder koffie aan een maandag begin. Doe maar.', english: 'As if I\'d start a Monday without coffee. Go ahead / yes please.' },
      { speaker: 'A', dutch: 'Die machine doet het weer niet goed. Ik heb al drie keer gedrukt.', english: 'That machine isn\'t working properly again. I\'ve already pressed it three times.' },
      { speaker: 'B', dutch: 'Geef eens. Je moet er echt hard op drukken, zo.', english: 'Let me try. You really have to press it hard, like this.' },
      { speaker: 'A', dutch: 'Oh. Dat wist ik niet. Al hoe lang werk jij hier?', english: 'Oh. I didn\'t know that. How long have you worked here?' },
      { speaker: 'B', dutch: 'Vijf jaar. De machine is er al zes. We kennen elkaar goed.', english: 'Five years. The machine has been here for six. We know each other well.' },
      { speaker: 'A', dutch: 'Zeg, heb jij die mail van Joost al gelezen?', english: 'Hey, did you read that email from Joost yet?' },
      { speaker: 'B', dutch: 'Nee. Is het erg?', english: 'No. Is it bad?' },
      { speaker: 'A', dutch: 'Vergadering. Vrijdagmiddag. Verplicht.', english: 'Meeting. Friday afternoon. Mandatory.' },
      { speaker: 'B', dutch: 'Vrijdagmiddag?! Joost is echt niet normaal.', english: 'Friday afternoon?! Joost is genuinely not normal.' },
      { speaker: 'A', dutch: 'Nou.', english: 'Right. / Tell me about it.' },
      { speaker: 'B', dutch: 'Oké. Eerst deze koffie opdrinken. Dan pas boos worden.', english: 'Okay. First finish this coffee. Get angry after.' },
      { speaker: 'A', dutch: 'Goed plan.', english: 'Good plan.' },
    ],
    expressions: [
      { dutch: 'Doe maar', english: 'Go ahead / yes please / sure', note: 'One of the most Dutch phrases ever. Casual way to agree or accept an offer. You\'ll hear this everywhere.' },
      { dutch: 'Zeg', english: 'Hey / listen / by the way', note: 'Used to introduce something new or get someone\'s attention. Like tapping someone on the shoulder with words.' },
      { dutch: 'Echt niet normaal', english: 'Genuinely unbelievable / out of order', note: 'Dutch people say this constantly. "Niet normaal" can mean amazing OR terrible — tone decides.' },
      { dutch: 'Nou', english: 'Right / yeah / well / tell me about it', note: 'The most flexible Dutch word. One "Nou" can mean agreement, resignation, surprise, or "let\'s move on".' },
      { dutch: 'Dan pas', english: 'Only then / after that', note: '"Dan pas" sets a clear order. "Eerst X, dan pas Y" = do X before even thinking about Y.' },
      { dutch: 'Verplicht', english: 'Mandatory / compulsory', note: 'Dreaded word in any language. In Dutch offices, a "verplichte vergadering" on vrijdagmiddag is a war crime.' },
    ],
  },
  {
    id: 'weekend-plannen',
    title: 'Weekend Plans',
    dutchTitle: 'Wat doe jij dit weekend?',
    emoji: '📅',
    description: 'Making plans, rescheduling, the Dutch way',
    level: 'A1',
    context: 'Donderdag. Emma appte Daan. Nu bellen ze even.',
    speakers: { A: 'Emma', B: 'Daan' },
    lines: [
      { speaker: 'A', dutch: 'Hé, zaterdag nog iets?', english: 'Hey, anything on Saturday?' },
      { speaker: 'B', dutch: 'Even kijken in mijn agenda... nee, niks.', english: 'Let me check my diary... no, nothing.' },
      { speaker: 'A', dutch: 'Bioscoop? Die nieuwe film met Carice van Houten.', english: 'Cinema? That new film with Carice van Houten.' },
      { speaker: 'B', dutch: 'Oh ja! Schijnt heel goed te zijn. Hoe laat?', english: 'Oh yes! Apparently really good. What time?' },
      { speaker: 'A', dutch: 'Avondfilm. Acht uur. Dan eerst ergens eten?', english: 'Evening showing. Eight o\'clock. Dinner somewhere first?' },
      { speaker: 'B', dutch: 'Ja leuk. Die nieuwe Surinaamse tent bij jou in de buurt?', english: 'Yes nice. That new Surinamese place near you?' },
      { speaker: 'A', dutch: 'Oeh, die wil ik ook al een tijdje proberen. Top!', english: 'Ooh, I\'ve wanted to try that for a while too. Great!' },
      { speaker: 'B', dutch: 'Even reserveren want het is altijd vol.', english: 'Better make a reservation because it\'s always full.' },
      { speaker: 'A', dutch: 'Doe ik. Zeven uur bij jou voor de deur?', english: 'I\'ll do it. Seven o\'clock at your front door?' },
      { speaker: 'B', dutch: 'Prima. Oh wacht, ik moet wel op tijd weg want de laatste tram...', english: 'Fine. Oh wait, I do need to leave on time because the last tram...' },
      { speaker: 'A', dutch: 'Daan. We gaan met de fiets.', english: 'Daan. We\'re going by bike.' },
      { speaker: 'B', dutch: 'O ja. Natuurlijk. Tot zaterdag!', english: 'Oh yeah. Of course. See you Saturday!' },
    ],
    expressions: [
      { dutch: 'Even kijken', english: 'Let me check / just looking', note: '"Even" softens everything in Dutch. "Even kijken" = give me a sec to check. You\'ll say this ten times a day.' },
      { dutch: 'Schijnt ... te zijn', english: 'Apparently it is / it\'s supposed to be', note: '"Schijnen" used this way = reportedly or apparently. Great for recommending things you haven\'t tried yourself.' },
      { dutch: 'In de buurt', english: 'Nearby / in the area', note: '"In jouw buurt" = near you. "De buurt" = the neighbourhood. Very useful for giving directions.' },
      { dutch: 'Al een tijdje', english: 'For a while already', note: 'Adds "I\'ve been meaning to" energy. "Al een tijdje willen" = been wanting to for ages.' },
      { dutch: 'Even reserveren', english: 'Better make a reservation / just book it', note: '"Even" again — makes the action feel quick and casual, even if it isn\'t.' },
      { dutch: 'We gaan met de fiets', english: 'We\'re going by bike', note: 'The most Dutch sentence in this entire app. In the Netherlands this is always the answer.' },
    ],
  },
  {
    id: 'trein-vertraging',
    title: 'Train Delay',
    dutchTitle: 'De trein heeft vertraging',
    emoji: '🚆',
    description: 'Strangers bonding on a platform — a Dutch national sport',
    level: 'A2',
    context: 'Perron 7, Utrecht Centraal. Het bord zegt "vertraging onbekend". Fatima en Bas staan al twintig minuten te wachten.',
    speakers: { A: 'Fatima', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Weet jij ook niet wat er aan de hand is?', english: 'Do you also not know what\'s going on?' },
      { speaker: 'B', dutch: 'Nee. Het bord zegt al een kwartier "vertraging onbekend".', english: 'No. The board has been saying "delay unknown" for fifteen minutes.' },
      { speaker: 'A', dutch: 'Onbekend. Geweldig.', english: 'Unknown. Wonderful. (sarcastic)' },
      { speaker: 'B', dutch: 'Heb je de NS-app?', english: 'Do you have the NS app?' },
      { speaker: 'A', dutch: 'Die zegt ook niks. Een seinstoring ergens, denk ik.', english: 'That says nothing either. A signal failure somewhere, I think.' },
      { speaker: 'B', dutch: 'Toch te gek. Ik betaal tweehonderd euro per maand voor dit abonnement.', english: 'Absolutely ridiculous. I pay two hundred euros a month for this subscription.' },
      { speaker: 'A', dutch: 'Ik ook. En toch staan we hier.', english: 'Me too. And yet here we stand.' },
      { speaker: 'B', dutch: 'Heb jij een vergadering?', english: 'Do you have a meeting?' },
      { speaker: 'A', dutch: 'Ja, om negen uur. Jij?', english: 'Yes, at nine o\'clock. You?' },
      { speaker: 'B', dutch: 'Ja. Zelfde tijdstip. Stuur maar een appje naar je baas.', english: 'Yes. Same time. Just send a WhatsApp to your boss.' },
      { speaker: 'A', dutch: '"Sorry, NS." Ze begrijpt het wel.', english: '"Sorry, NS." She\'ll understand.' },
      { speaker: 'B', dutch: 'Tegenwoordig is dat gewoon een officiële reden.', english: 'Nowadays that\'s just an official reason.' },
      { speaker: 'A', dutch: 'Echt zo. Oh, hij komt eraan!', english: 'So true. Oh, it\'s coming!' },
      { speaker: 'B', dutch: 'Eindelijk! Instappen maar.', english: 'Finally! Let\'s get on.' },
    ],
    expressions: [
      { dutch: 'Wat is er aan de hand?', english: 'What\'s going on? / What\'s the matter?', note: 'Go-to phrase when something\'s wrong or confusing. Works for train delays, arguments, weird smells — everything.' },
      { dutch: 'Toch te gek', english: 'Absolutely ridiculous / unbelievable', note: '"Te gek" = too crazy. Can be positive (insanely cool) or negative (insanely bad). Context decides.' },
      { dutch: 'En toch', english: 'And yet / still', note: 'Shows a contradiction. "I paid €200... and yet here I stand." Very good for expressing irony.' },
      { dutch: 'Stuur maar een appje', english: 'Just send a WhatsApp message', note: '"Appje sturen" = send a WhatsApp. The Dutch verb "appen" literally means to WhatsApp someone.' },
      { dutch: 'Tegenwoordig', english: 'Nowadays / these days', note: 'Easy word to sprinkle into conversation to sound fluent. "Tegenwoordig is dat normaal" = that\'s normal nowadays.' },
      { dutch: 'Instappen maar', english: 'Let\'s get on / time to board', note: '"Instappen" = to get in/on (transport). "Maar" here makes it feel like "finally, let\'s go".' },
    ],
  },
  {
    id: 'albert-heijn',
    title: 'At the Albert Heijn',
    dutchTitle: 'Bij de Albert Heijn',
    emoji: '🧡',
    description: 'A very Dutch supermarket experience',
    level: 'A1',
    context: 'Zaterdagochtend bij de AH. Druk. Yara staat bij de zelfscankassa. Die doet het niet.',
    speakers: { A: 'Yara', B: 'Medewerker Tim' },
    lines: [
      { speaker: 'A', dutch: 'Excuseer, deze kassa doet het niet. Hij zegt steeds "onbekend artikel".', english: 'Excuse me, this checkout isn\'t working. It keeps saying "unknown item".' },
      { speaker: 'B', dutch: 'Wat heeft u gescand?', english: 'What did you scan?' },
      { speaker: 'A', dutch: 'De komkommer. Maar ik heb de sticker goed gescand, echt.', english: 'The cucumber. But I scanned the sticker correctly, really.' },
      { speaker: 'B', dutch: 'Heeft u ook de bonus-app?', english: 'Do you also have the bonus app?' },
      { speaker: 'A', dutch: 'Ja, maar ik snap hem nooit helemaal.', english: 'Yes, but I never fully understand it.' },
      { speaker: 'B', dutch: 'Geeft niet. Mag ik uw telefoon even?', english: 'That\'s okay. Can I borrow your phone for a moment?' },
      { speaker: 'A', dutch: 'Hier. Oh en ik wilde ook vragen — waar is de hagelslag?', english: 'Here. Oh and I also wanted to ask — where is the hagelslag?' },
      { speaker: 'B', dutch: 'Gangpad drie, bij het broodbeleg. Links.', english: 'Aisle three, with the bread toppings. On the left.' },
      { speaker: 'A', dutch: 'Dankjewel. En de komkommer?', english: 'Thank you. And the cucumber?' },
      { speaker: 'B', dutch: 'Ik heb het opgelost. U kunt doorgaan.', english: 'I\'ve sorted it. You can continue.' },
      { speaker: 'A', dutch: 'Super. Betalen met iDEAL kan hier toch?', english: 'Great. I can pay with iDEAL here, right?' },
      { speaker: 'B', dutch: 'Pin of contant. iDEAL niet bij de zelfscankassa.', english: 'Card or cash. No iDEAL at the self-checkout.' },
      { speaker: 'A', dutch: 'Oh. Oké. Dan maar pinnen.', english: 'Oh. Okay. Then I\'ll just use card.' },
    ],
    expressions: [
      { dutch: 'Geeft niet', english: 'That\'s okay / no worries / doesn\'t matter', note: 'Literally "doesn\'t give". One of the most reassuring phrases in Dutch. Use it to say "no problem at all".' },
      { dutch: 'Mag ik even...?', english: 'Can I just...? / May I quickly...?', note: '"Even" makes requests sound polite and quick. "Mag ik even?" is THE Dutch way to ask for something briefly.' },
      { dutch: 'Ik heb het opgelost', english: 'I\'ve sorted it / I\'ve solved it', note: '"Oplossen" = to solve. Super useful — problems in the Netherlands always need "oplossen".' },
      { dutch: 'U kunt doorgaan', english: 'You can continue / carry on', note: 'Formal but very common in shops, offices, hospitals. "Doorgaan" = to continue.' },
      { dutch: 'Dan maar', english: 'Then I\'ll just / in that case', note: '"Dan maar pinnen" = okay fine, I\'ll just pay by card then. "Dan maar" accepts a situation a bit reluctantly.' },
      { dutch: 'Hagelslag', english: 'Chocolate sprinkles (for on bread)', note: 'The most Dutch food item. Dutch people put chocolate sprinkles on buttered bread for breakfast. Not a joke.' },
    ],
  },
  {
    id: 'verjaardag-party',
    title: 'Birthday Plans',
    dutchTitle: 'Verjaardag plannen',
    emoji: '🎂',
    description: 'Organising a surprise party — Dutch edition',
    level: 'A2',
    context: 'Roos belt Joep. Lotte wordt zaterdag dertig en niemand heeft iets geregeld.',
    speakers: { A: 'Roos', B: 'Joep' },
    lines: [
      { speaker: 'A', dutch: 'Joep. Lotte. Zaterdag. Dertig. Wat doen we?', english: 'Joep. Lotte. Saturday. Thirty. What are we doing?' },
      { speaker: 'B', dutch: 'O nee. Ik had dat helemaal vergeten.', english: 'Oh no. I had completely forgotten that.' },
      { speaker: 'A', dutch: 'Dat weet ik. Daarom bel ik jou.', english: 'I know. That\'s why I\'m calling you.' },
      { speaker: 'B', dutch: 'Oké oké. Verrassingsfeestje?', english: 'Okay okay. Surprise party?' },
      { speaker: 'A', dutch: 'Ze weet van niks. Bij mij thuis kan.', english: 'She has no idea. My place works.' },
      { speaker: 'B', dutch: 'Hoeveel mensen?', english: 'How many people?' },
      { speaker: 'A', dutch: 'Niet te groot. Twintig man ofzo. Ik maak een appgroep aan.', english: 'Not too big. About twenty people. I\'ll create a WhatsApp group.' },
      { speaker: 'B', dutch: 'Let erop dat Lotte er niet in zit.', english: 'Make sure Lotte\'s not in it.' },
      { speaker: 'A', dutch: 'Ja hallo, dat snap ik zelf ook wel.', english: 'Oh come on, I know that myself.' },
      { speaker: 'B', dutch: 'Sorry sorry. Ik regel de drank.', english: 'Sorry sorry. I\'ll sort the drinks.' },
      { speaker: 'A', dutch: 'Ik zorg voor eten. En iemand moet haar erheen lokken.', english: 'I\'ll handle food. And someone needs to lure her there.' },
      { speaker: 'B', dutch: 'Sanne. Die liegt het beste van ons allemaal.', english: 'Sanne. She\'s the best liar out of all of us.' },
      { speaker: 'A', dutch: 'Ideaal. Oké, ik app haar nu.', english: 'Perfect. Okay, I\'ll WhatsApp her now.' },
      { speaker: 'B', dutch: 'En Roos? Geen taart van de AH dit keer. Die was vorig jaar droog.', english: 'And Roos? No cake from the AH this time. That one was dry last year.' },
      { speaker: 'A', dutch: 'Joep. Focus.', english: 'Joep. Focus.' },
    ],
    expressions: [
      { dutch: 'Ze weet van niks', english: 'She has no idea / she doesn\'t know anything', note: 'Essential for surprise planning. "Van niks weten" = to have no clue about something.' },
      { dutch: 'Twintig man ofzo', english: 'About twenty people or so', note: '"Man" is used informally to count people regardless of gender. "Ofzo" adds a casual approximation.' },
      { dutch: 'Ja hallo', english: 'Come on / obviously / give me some credit', note: 'Mild but firm. "Ja hallo" means "seriously? I\'m not stupid." Not rude, just direct — very Dutch.' },
      { dutch: 'Ik regel de drank', english: 'I\'ll sort the drinks / I\'ll handle the drinks', note: '"Regelen" = to sort/arrange. Dutch people "regelen" everything. Very action-oriented word.' },
      { dutch: 'Erheen lokken', english: 'To lure someone there', note: '"Lokken" = to lure/tempt/entice. Used for getting someone somewhere under a false pretence.' },
      { dutch: 'Ideaal', english: 'Perfect / ideal / that works great', note: 'Casual "perfect". Dutch people say "ideaal!" when something fits exactly. More enthusiastic than it looks.' },
    ],
  },
  {
    id: 'weer-klagen',
    title: 'About the Weather',
    dutchTitle: 'Weer klagen over het weer',
    emoji: '🌧️',
    description: 'The Dutch national pastime',
    level: 'A1',
    context: 'Buiten. Het regent. Het regende gisteren ook. En eergisteren. Henk en Marjolein staan bij de brievenbus.',
    speakers: { A: 'Henk', B: 'Marjolein' },
    lines: [
      { speaker: 'A', dutch: 'Goedemorgen Marjolein. Wat een weer, hè?', english: 'Good morning Marjolein. What weather, huh?' },
      { speaker: 'B', dutch: 'Vreselijk. Ik ben al drie keer op de fiets gevallen dit jaar.', english: 'Terrible. I\'ve already fallen off my bike three times this year.' },
      { speaker: 'A', dutch: 'Door de regen?', english: 'Because of the rain?' },
      { speaker: 'B', dutch: 'Regen én wind. Gisteren woei mijn paraplu binnenstebuiten.', english: 'Rain AND wind. Yesterday my umbrella blew inside out.' },
      { speaker: 'A', dutch: 'Haha! Paraplu\'s zijn nutteloos hier, eerlijk gezegd.', english: 'Haha! Umbrellas are useless here, honestly.' },
      { speaker: 'B', dutch: 'Toch koop ik er elk jaar een nieuwe. En hij gaat elk jaar kapot.', english: 'And yet I buy a new one every year. And it breaks every year.' },
      { speaker: 'A', dutch: 'Zeggen ze niet dat het zondag beter wordt?', english: 'Don\'t they say it\'ll be better on Sunday?' },
      { speaker: 'B', dutch: 'Dat zeggen ze elke week. Ik geloof de buienradar allang niet meer.', english: 'They say that every week. I stopped trusting the weather app long ago.' },
      { speaker: 'A', dutch: 'Maar goed. Wat wil je. Het is Nederland.', english: 'But well. What do you expect. It\'s the Netherlands.' },
      { speaker: 'B', dutch: 'Zo is dat. Hoe gaat het verder met jou?', english: 'That\'s right. How are you otherwise?' },
      { speaker: 'A', dutch: 'Goed hoor. Ik ga maar. Hou je droog!', english: 'Good thanks. I\'ll be off. Stay dry!' },
      { speaker: 'B', dutch: 'Jij ook! Als dat lukt tenminste.', english: 'You too! If that\'s even possible.' },
    ],
    expressions: [
      { dutch: 'Wat een weer, hè?', english: 'What weather, huh?', note: 'The universal Dutch conversation opener. Safe with strangers, neighbours, colleagues, anyone. Always works.' },
      { dutch: 'Binnenstebuiten', english: 'Inside out / upside down', note: 'Literally "inside-to-outside". Happens to every umbrella in the Netherlands at least once per autumn.' },
      { dutch: 'Eerlijk gezegd', english: 'Honestly / to be honest', note: 'Adds honesty to a statement. "Eerlijk gezegd snap ik het niet" = to be honest, I don\'t get it.' },
      { dutch: 'Allang niet meer', english: 'Not anymore for a long time / haven\'t for ages', note: '"Allang" = for a long time already. "Allang niet meer" = stopped doing something ages ago.' },
      { dutch: 'Maar goed, wat wil je', english: 'But well, what do you expect', note: 'The Dutch phrase for accepting something annoying but inevitable. Shrug energy in word form.' },
      { dutch: 'Hou je droog', english: 'Stay dry', note: 'Dutch farewell for rainy days. More realistic than "have a nice day" given the climate.' },
    ],
  },
  {
    id: 'huisgenoten-klusjes',
    title: 'Housemate Chores',
    dutchTitle: 'Wie doet wat?',
    emoji: '🧹',
    description: 'A tense negotiation in a Utrecht studenthouse',
    level: 'A2',
    context: 'Keuken, studentenhuis Utrecht. De vaat staat er al twee dagen. Lena heeft het gezien. Thomas ook, maar deed alsof niet.',
    speakers: { A: 'Lena', B: 'Thomas' },
    lines: [
      { speaker: 'A', dutch: 'Thomas.', english: 'Thomas.' },
      { speaker: 'B', dutch: 'Hm?', english: 'Hm?' },
      { speaker: 'A', dutch: 'De keuken.', english: 'The kitchen.' },
      { speaker: 'B', dutch: 'Ja ik weet het, ik doe het straks.', english: 'Yeah I know, I\'ll do it later.' },
      { speaker: 'A', dutch: '"Straks" zei je gisteren ook.', english: 'You said "later" yesterday too.' },
      { speaker: 'B', dutch: 'Ik had het echt druk! Sorry. Ik doe het nu meteen.', english: 'I was genuinely busy! Sorry. I\'ll do it right now.' },
      { speaker: 'A', dutch: 'En de badkamer dan? Die is ook aan de beurt.', english: 'And the bathroom then? That needs doing too.' },
      { speaker: 'B', dutch: 'Oké, ik doe de keuken, aanrecht én vloer. Dan doe jij de badkamer?', english: 'Okay, I\'ll do the kitchen, counter AND floor. Then you do the bathroom?' },
      { speaker: 'A', dutch: 'Die heb ik vorige week ook al gedaan hoor.', english: 'I already did that last week too, you know.' },
      { speaker: 'B', dutch: 'Oké oké. Ik doe alles. Maar kunnen we dan een poetsrooster maken?', english: 'Okay okay. I\'ll do everything. But can we make a cleaning schedule then?' },
      { speaker: 'A', dutch: 'Dat stel ik al voor sinds september.', english: 'I\'ve been suggesting that since September.' },
      { speaker: 'B', dutch: 'Je had gelijk. Ik geef het toe.', english: 'You were right. I admit it.' },
      { speaker: 'A', dutch: 'Dankjewel. Ik maak vanavond een schema in Notion.', english: 'Thank you. I\'ll make a schedule in Notion tonight.' },
      { speaker: 'B', dutch: 'Goed. Kan ik dan ook zien wanneer jij niet hebt gestofzuigd?', english: 'Good. Then I can also see when you haven\'t vacuumed?' },
      { speaker: 'A', dutch: 'Thomas.', english: 'Thomas.' },
      { speaker: 'B', dutch: 'Ik ga al.', english: 'I\'m going.' },
    ],
    expressions: [
      { dutch: 'Straks', english: 'Later / in a bit / shortly', note: 'Vague Dutch time word. "Straks" can mean in five minutes or in five hours. Housemates know the difference.' },
      { dutch: 'Ik had het echt druk', english: 'I was genuinely busy', note: '"Druk hebben" = to be busy. "Echt" adds sincerity (or the attempt of it).' },
      { dutch: 'Nu meteen', english: 'Right now / this instant', note: 'More urgent than just "nu". "Nu meteen" means no more delays — do it this second.' },
      { dutch: 'Aan de beurt zijn', english: 'To be someone\'s turn', note: '"Wiens beurt is het?" = whose turn is it? Core vocabulary for any shared living situation.' },
      { dutch: 'Ik geef het toe', english: 'I admit it / I concede', note: '"Toegeven" = to admit/give in. A rare but valued phrase from a housemate who never cleans.' },
      { dutch: 'Ik ga al', english: 'I\'m going / I\'m already on my way', note: 'Said when you\'ve been told to do something and you\'re (finally) doing it. Slightly defensive.' },
    ],
  },
  {
    id: 'nieuwe-baan',
    title: 'New Job',
    dutchTitle: 'Ik heb een nieuwe baan!',
    emoji: '🎉',
    description: 'Good news travels fast, especially via WhatsApp',
    level: 'A2',
    context: 'Sophie stuurt een voice memo naar Rick. Dan belt hij haar meteen terug.',
    speakers: { A: 'Sophie', B: 'Rick' },
    lines: [
      { speaker: 'A', dutch: 'Rick! Ik heb een nieuwe baan!', english: 'Rick! I got a new job!' },
      { speaker: 'B', dutch: 'Wát?! Vertel! Nu! Alles!', english: 'What?! Tell me! Now! Everything!' },
      { speaker: 'A', dutch: 'Een startup in Amsterdam. UX design. Mijn drooombaan.', english: 'A startup in Amsterdam. UX design. My dream job.' },
      { speaker: 'B', dutch: 'Dat meen je niet. Hoe ben je erbij gekomen?', english: 'You can\'t be serious. How did you get it?' },
      { speaker: 'A', dutch: 'Via LinkedIn. Ze kwamen zelf naar mij toe.', english: 'Via LinkedIn. They came to me themselves.' },
      { speaker: 'B', dutch: 'Logisch. Jij bent gewoon goed.', english: 'Makes sense. You\'re just good at what you do.' },
      { speaker: 'A', dutch: 'Doe normaal.', english: 'Stop it / come off it.' },
      { speaker: 'B', dutch: 'Echt waar! Goed verdiend. Wanneer begin je?', english: 'I mean it! Well deserved. When do you start?' },
      { speaker: 'A', dutch: 'Volgende maand. Het voelt nog een beetje onwerkelijk.', english: 'Next month. It still feels a bit unreal.' },
      { speaker: 'B', dutch: 'Snap ik. Maar Sophie — dit moet gevierd worden.', english: 'I get that. But Sophie — this needs to be celebrated.' },
      { speaker: 'A', dutch: 'Vanavond een biertje?', english: 'A beer tonight?' },
      { speaker: 'B', dutch: 'Ik sta al bij de deur.', english: 'I\'m already at the door.' },
    ],
    expressions: [
      { dutch: 'Dat meen je niet', english: 'You can\'t be serious / no way!', note: '"Menen" = to mean/be serious. "Dat meen je niet!" = you\'re kidding me. Enthusiastic disbelief.' },
      { dutch: 'Hoe ben je erbij gekomen?', english: 'How did you get it? / How did that come about?', note: '"Ergens bij komen" = to come across something, to get something. Natural and casual.' },
      { dutch: 'Ze kwamen naar mij toe', english: 'They came to me', note: 'Direction matters in Dutch. "Naar mij toe" = towards me. "Naartoe" is a key direction word.' },
      { dutch: 'Doe normaal', english: 'Stop it / come off it / be normal', note: 'Literally "be normal." Dutch people say this to brush off a compliment. NOT rude — it\'s modest deflection.' },
      { dutch: 'Goed verdiend', english: 'Well deserved', note: 'Warm, genuine compliment. Acknowledges that someone earned something through hard work.' },
      { dutch: 'Ik sta al bij de deur', english: 'I\'m already at the door', note: 'Dutch efficiency. Why say "I\'ll come over" when you can already be there?' },
    ],
  },
  {
    id: 'ziek-thuis',
    title: 'Calling in Sick',
    dutchTitle: 'Ik ben ziek',
    emoji: '🤒',
    description: 'That awkward call to your Dutch manager',
    level: 'A2',
    context: 'Maandagochtend kwart voor negen. Mia heeft koorts maar belt toch. Ze hoopt dat Kevin opneemt, niet zijn assistent.',
    speakers: { A: 'Mia', B: 'Kevin' },
    lines: [
      { speaker: 'B', dutch: 'Kevin de Vries.', english: 'Kevin de Vries. (how Dutch people answer the phone)' },
      { speaker: 'A', dutch: 'Kevin, met Mia. Ik bel om te zeggen dat ik me niet goed voel.', english: 'Kevin, this is Mia. I\'m calling to say I\'m not feeling well.' },
      { speaker: 'B', dutch: 'Wat is er aan de hand?', english: 'What\'s the matter?' },
      { speaker: 'A', dutch: 'Koorts, keelpijn. Ik denk griep.', english: 'Fever, sore throat. I think flu.' },
      { speaker: 'B', dutch: 'Dan moet je thuis blijven. Geen discussie.', english: 'Then you need to stay home. No discussion.' },
      { speaker: 'A', dutch: 'Maar de deadline van donderdag...', english: 'But Thursday\'s deadline...' },
      { speaker: 'B', dutch: 'Mia. Thuis blijven.', english: 'Mia. Stay home.' },
      { speaker: 'A', dutch: 'Oké. Ik stuur de bestanden wel even door naar Pieter.', english: 'Okay. I\'ll just forward the files to Pieter.' },
      { speaker: 'B', dutch: 'Dat hoeft niet nu. Rust eerst uit.', english: 'You don\'t need to do that now. Rest first.' },
      { speaker: 'A', dutch: 'Ik vind het vervelend.', english: 'I feel bad about it.' },
      { speaker: 'B', dutch: 'Gezondheid gaat voor. Laat me weten hoe het morgen gaat.', english: 'Health comes first. Let me know how you\'re doing tomorrow.' },
      { speaker: 'A', dutch: 'Bedankt Kevin. Beterschap... aan mezelf dan maar.', english: 'Thanks Kevin. Get well soon... to myself then.' },
      { speaker: 'B', dutch: 'Haha. Beterschap Mia. Tot snel.', english: 'Haha. Get well soon Mia. See you soon.' },
    ],
    expressions: [
      { dutch: '[Naam].', english: '[Name]. (answering the phone)', note: 'Dutch people answer the phone with just their name. Always. "Met Mia" if calling, just "Kevin de Vries" if answering.' },
      { dutch: 'Geen discussie', english: 'No discussion / not up for debate', note: 'Direct Dutch management style. Short, clear, done. No negotiating.' },
      { dutch: 'Ik vind het vervelend', english: 'I feel bad about it / I\'m sorry about it', note: '"Vervelend vinden" = to find something unpleasant or to feel guilty about it. Very common.' },
      { dutch: 'Gezondheid gaat voor', english: 'Health comes first', note: 'A Dutch phrase that actually means it — Dutch managers often genuinely believe this. Rest, then work.' },
      { dutch: 'Laat me weten', english: 'Let me know', note: 'Essential phrase. "Laat het me weten" = let me know (about it). You\'ll use this every day.' },
      { dutch: 'Beterschap', english: 'Get well soon', note: 'THE Dutch phrase for sickness. Never say "get well soon" in Dutch — always "beterschap!" One word, warm, done.' },
    ],
  },
  {
    id: 'huurhuis-zoeken',
    title: 'Finding a Flat',
    dutchTitle: 'Een huis zoeken in Nederland',
    emoji: '🏠',
    description: 'The most relatable conversation for every expat in NL',
    level: 'B1',
    context: 'Ana (net verhuisd naar NL) en Sven (al drie jaar in Amsterdam) praten na de vergadering.',
    speakers: { A: 'Ana', B: 'Sven' },
    lines: [
      { speaker: 'A', dutch: 'Sven, ik zoek al vier maanden naar een woning. Ik word er écht gek van.', english: 'Sven, I\'ve been looking for a home for four months. It\'s genuinely driving me crazy.' },
      { speaker: 'B', dutch: 'Vier maanden is hier niks. Ik deed er zeven over.', english: 'Four months is nothing here. It took me seven.' },
      { speaker: 'A', dutch: 'Zeven maanden?!', english: 'Seven months?!' },
      { speaker: 'B', dutch: 'Welkom in Amsterdam. Wat is je budget?', english: 'Welcome to Amsterdam. What\'s your budget?' },
      { speaker: 'A', dutch: 'Tot 1400. Maar dan krijg je een kamer zonder raam blijkbaar.', english: 'Up to 1400. But apparently that gets you a room without a window.' },
      { speaker: 'B', dutch: 'Helaas klopt dat. Heb je al buiten Amsterdam gekeken?', english: 'Unfortunately that\'s true. Have you looked outside Amsterdam already?' },
      { speaker: 'A', dutch: 'Ja, maar ik heb geen auto en de fietsroutes zijn...', english: 'Yes, but I don\'t have a car and the cycling routes are...' },
      { speaker: 'B', dutch: 'Je moet gewoon een fiets kopen. Iedereen doet dat hier.', english: 'You just need to buy a bike. Everyone does that here.' },
      { speaker: 'A', dutch: 'En als hij gestolen wordt?', english: 'And if it gets stolen?' },
      { speaker: 'B', dutch: 'Dan koop je een nieuwe. Zo werkt het hier.', english: 'Then you buy a new one. That\'s how it works here.' },
      { speaker: 'A', dutch: 'Fijn. En de sociale huurlijst?', english: 'Great. And the social housing waiting list?' },
      { speaker: 'B', dutch: 'Tien jaar. Ik heb me wel ingeschreven, voor de grap.', english: 'Ten years. I did register, for laughs.' },
      { speaker: 'A', dutch: 'Dit is te waanzinnig voor woorden.', english: 'This is absolutely beyond belief.' },
      { speaker: 'B', dutch: 'Yep. Maar je went eraan. Ik hoor het als ik iets hoor.', english: 'Yep. But you get used to it. I\'ll let you know if I hear anything.' },
      { speaker: 'A', dutch: 'Dankjewel. Welkom in Nederland inderdaad.', english: 'Thank you. Welcome to the Netherlands indeed.' },
    ],
    expressions: [
      { dutch: 'Ik word er gek van', english: 'It\'s driving me crazy', note: 'Strong frustration. "Ergens gek van worden" = to be driven insane by something. Very relatable in NL housing market.' },
      { dutch: 'Helaas klopt dat', english: 'Unfortunately that\'s true', note: '"Kloppen" = to be correct/true. "Dat klopt" = that\'s right. "Helaas" = unfortunately. Painful combination.' },
      { dutch: 'Voor de grap', english: 'For laughs / as a joke / just for fun', note: 'Doing something without any real hope of it working. Registering for social housing in NL = for the grap.' },
      { dutch: 'Te waanzinnig voor woorden', english: 'Beyond words / absolutely insane', note: '"Te [adj] voor woorden" = so [something] it can\'t be described. Strong expression of disbelief.' },
      { dutch: 'Je went eraan', english: 'You get used to it', note: '"Wennen aan" = to get used to. "Je went eraan" = you\'ll adjust. Often said about Dutch weather, directness, and housing.' },
      { dutch: 'Ik hoor het als ik iets hoor', english: 'I\'ll let you know if I hear anything', note: 'Literally "I\'ll hear it when I hear something." The Dutch way of promising to pass on info without committing.' },
    ],
  },
  {
    id: 'fiets-gestolen',
    title: 'Stolen Bike',
    dutchTitle: 'Mijn fiets is weg!',
    emoji: '😤',
    description: 'Every Dutch person has lived this moment',
    level: 'A2',
    context: 'Nadia staat voor de fietsenrekken bij Amsterdam Centraal. Haar fiets is weg. Ze belt Bas.',
    speakers: { A: 'Nadia', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Bas. Mijn fiets is weg.', english: 'Bas. My bike is gone.' },
      { speaker: 'B', dutch: 'Weg als in... gestolen?', english: 'Gone as in... stolen?' },
      { speaker: 'A', dutch: 'Ik had hem hier neergezet met een goed slot. Hij is er gewoon niet meer.', english: 'I parked him here with a good lock. He\'s just not there anymore.' },
      { speaker: 'B', dutch: 'Hij. Je zegt "hij".', english: 'He. You said "he".' },
      { speaker: 'A', dutch: 'Ik had een band met die fiets, Bas.', english: 'I had a bond with that bike, Bas.' },
      { speaker: 'B', dutch: 'Oké. Heb je aangifte gedaan?', english: 'Okay. Have you filed a police report?' },
      { speaker: 'A', dutch: 'Ja. Ze zeiden dat de kans klein is.', english: 'Yes. They said the chances are small.' },
      { speaker: 'B', dutch: 'Die zeggen dat altijd. En je verzekering?', english: 'They always say that. And your insurance?' },
      { speaker: 'A', dutch: 'Dekt het. Maar ik moet nu lopend naar huis.', english: 'It covers it. But I have to walk home now.' },
      { speaker: 'B', dutch: 'Lopen?! In Amsterdam?! Dat doe je toch niet.', english: 'Walk?! In Amsterdam?! You can\'t do that.' },
      { speaker: 'A', dutch: 'Wat moet ik dan?', english: 'What am I supposed to do then?' },
      { speaker: 'B', dutch: 'Mijn reservefiets staat bij mij voor de deur. Kom maar.', english: 'My spare bike is at my front door. Come over.' },
      { speaker: 'A', dutch: 'Je bent een engel.', english: 'You\'re an angel.' },
      { speaker: 'B', dutch: 'En Nadia? Dit keer twee sloten.', english: 'And Nadia? Two locks this time.' },
      { speaker: 'A', dutch: 'Drie.', english: 'Three.' },
    ],
    expressions: [
      { dutch: 'Weg als in...?', english: 'Gone as in...?', note: 'Asking for clarification with "als in" = "as in". Very natural way to double-check what someone means.' },
      { dutch: 'Een band hebben met', english: 'To have a bond with / to be attached to', note: '"Een band hebben met" = to have a connection or attachment to someone (or something, like a bike).' },
      { dutch: 'Aangifte doen', english: 'To file a police report', note: 'You "do aangifte" at the politie. Essential vocabulary for bike theft, which happens approximately every 47 seconds in NL.' },
      { dutch: 'Dat doe je toch niet', english: 'You can\'t do that / that\'s not done', note: '"Dat doe je niet" = that\'s not something you do. The "toch" adds mild disbelief or disapproval.' },
      { dutch: 'Wat moet ik dan?', english: 'What am I supposed to do then?', note: '"Moeten" = must/should. "Wat moet ik dan?" = slightly helpless "well what then?" Very natural.' },
      { dutch: 'Je bent een engel', english: 'You\'re an angel', note: 'Warm expression of gratitude. More heartfelt than "bedankt". Use when someone really saves you.' },
    ],
  },
  {
    id: 'sinterklaas',
    title: 'Sinterklaas',
    dutchTitle: 'Het is vijf december!',
    emoji: '🎅',
    description: 'The most Dutch evening of the year',
    level: 'A2',
    context: '5 december, middag. Ellen en Paul bereiden de avond voor. De kinderen zijn op school.',
    speakers: { A: 'Ellen', B: 'Paul' },
    lines: [
      { speaker: 'A', dutch: 'Paul, heb jij de surprises al ingepakt?', english: 'Paul, have you already wrapped the surprises?' },
      { speaker: 'B', dutch: 'Bijna. Ik was nog bezig met het gedicht voor je moeder.', english: 'Almost. I was still working on the poem for your mum.' },
      { speaker: 'A', dutch: 'Is het lief of gemeen?', english: 'Is it sweet or mean?' },
      { speaker: 'B', dutch: 'Een beetje van allebei. Zoals het hoort.', english: 'A bit of both. As it should be.' },
      { speaker: 'A', dutch: 'Haha. Ze mag het hopen. Hoe laat komen ze?', english: 'Haha. She\'d better brace herself. What time are they coming?' },
      { speaker: 'B', dutch: 'Half zes. De kinderen weten nog van niks.', english: 'Half past five. The kids still don\'t know anything.' },
      { speaker: 'A', dutch: 'Die van Emma schijnt echt geweldig te zijn dit jaar.', english: 'Emma\'s surprise is apparently really great this year.' },
      { speaker: 'B', dutch: 'Dat zegt ze zelf, ja. We zullen zien.', english: 'She says so herself, yes. We\'ll see.' },
      { speaker: 'A', dutch: 'Heb jij pepernoten gekocht?', english: 'Did you buy pepernoten?' },
      { speaker: 'B', dutch: 'Twee zakken. En speculaas. En chocoladeletters.', english: 'Two bags. And speculaas. And chocolate letters.' },
      { speaker: 'A', dutch: 'Welke letter heb je voor mij?', english: 'Which letter did you get for me?' },
      { speaker: 'B', dutch: 'Dat verklap ik niet. Dat is de verrassing.', english: 'I\'m not going to reveal that. That\'s the surprise.' },
      { speaker: 'A', dutch: 'Het is gewoon een E toch.', english: 'It\'s just an E, isn\'t it.' },
      { speaker: 'B', dutch: 'Het is een E.', english: 'It\'s an E.' },
    ],
    expressions: [
      { dutch: 'Zoals het hoort', english: 'As it should be / as is proper', note: '"Horen" used this way = to be appropriate/proper. "Zoals het hoort" = the right and proper way. Very Dutch.' },
      { dutch: 'Ze mag het hopen', english: 'She\'d better brace herself / she can only hope', note: '"Mag het hopen" is used when someone is about to receive something — a surprise, criticism, or a poem.' },
      { dutch: 'We zullen zien', english: 'We\'ll see', note: 'Universal skeptical phrase. Dutch "we zullen zien" carries exactly the same skeptical energy as English "we\'ll see".' },
      { dutch: 'Dat verklap ik niet', english: 'I\'m not going to reveal/spoil that', note: '"Verkappen" = to reveal a secret or spoil a surprise. Perfect for Sinterklaas season.' },
      { dutch: 'Pepernoten', english: 'Small spiced biscuits', note: 'THE snack of Sinterklaas. Small, round, spiced cookies thrown by Zwarte Piet (or Sinterklaas). Bags appear in shops from September.' },
      { dutch: 'Chocoladeletter', english: 'Chocolate letter', note: 'Sinterklaas tradition: you get a chocolate in the shape of your first initial. Asking which letter = asking what gift.' },
    ],
  },
  {
    id: 'etentje-organiseren',
    title: 'Dinner Party',
    dutchTitle: 'Etentje bij mij thuis',
    emoji: '🍷',
    description: 'Dutch dinner planning — practical, direct, no fuss',
    level: 'A2',
    context: 'Fleur en Diederik lopen na het werk samen naar de fiets. Fleur heeft zin om te koken.',
    speakers: { A: 'Fleur', B: 'Diederik' },
    lines: [
      { speaker: 'A', dutch: 'Diederik, we moeten binnenkort een etentje doen.', english: 'Diederik, we need to do a dinner soon.' },
      { speaker: 'B', dutch: 'Ja! Bij jou? Jij kookt tenminste lekker.', english: 'Yes! At yours? At least you cook well.' },
      { speaker: 'A', dutch: 'Dankjewel. Wat een compliment.', english: 'Thank you. What a compliment.' },
      { speaker: 'B', dutch: 'Sorry. Ik bedoel: ik kook ook lekker maar... nee, jij kookt beter.', english: 'Sorry. I mean: I cook well too but... no, you cook better.' },
      { speaker: 'A', dutch: 'Haha. Welk weekend werkt voor jou?', english: 'Haha. Which weekend works for you?' },
      { speaker: 'B', dutch: 'Niet dit weekend. Over twee weken?', english: 'Not this weekend. In two weeks?' },
      { speaker: 'A', dutch: 'Goed. Ik twijfel nog tussen pasta en een Indonesisch gerecht.', english: 'Good. I\'m still torn between pasta and an Indonesian dish.' },
      { speaker: 'B', dutch: 'Indonesisch. Zonder twijfel.', english: 'Indonesian. Without a doubt.' },
      { speaker: 'A', dutch: 'Oké. Iemand met dieetwensen weet je?', english: 'Okay. Anyone with dietary requirements do you know?' },
      { speaker: 'B', dutch: 'Lars eet geen vlees. En Nina is lactose-intolerant maar die vraagt er zelf nooit om, dus...', english: 'Lars doesn\'t eat meat. And Nina is lactose intolerant but she never asks about it herself, so...' },
      { speaker: 'A', dutch: 'Dan houd ik er toch rekening mee. Iedereen brengt een fles wijn?', english: 'Then I\'ll take it into account anyway. Everyone brings a bottle of wine?' },
      { speaker: 'B', dutch: 'Ja. En ik neem een taart mee. Van de bakker, niet van de AH.', english: 'Yes. And I\'ll bring a cake. From the bakery, not from the AH.' },
      { speaker: 'A', dutch: 'Goed idee. Dan is het geregeld!', english: 'Good idea. Then it\'s sorted!' },
    ],
    expressions: [
      { dutch: 'Tenminste', english: 'At least', note: 'A tiny word that carries a lot. "Jij kookt tenminste lekker" = at least YOU cook well (implying others don\'t).' },
      { dutch: 'Zonder twijfel', english: 'Without a doubt', note: 'Confident, decisive. Dutch people appreciate decisiveness. "Zonder twijfel" shuts down a decision fast.' },
      { dutch: 'Toch rekening mee houden', english: 'Take it into account anyway', note: '"Rekening houden met" = to consider/account for. "Toch" adds "even so" — doing it regardless of whether asked.' },
      { dutch: 'Dan is het geregeld', english: 'Then it\'s all sorted', note: '"Geregeld" = sorted/arranged. Satisfying phrase when a plan comes together. Very Dutch efficiency.' },
      { dutch: 'Ik twijfel nog', english: 'I\'m still undecided / still torn', note: '"Twijfelen" = to doubt/hesitate. "Ik twijfel nog" = I\'m still going back and forth on it.' },
      { dutch: 'Van de bakker, niet van de AH', english: 'From the bakery, not from Albert Heijn', note: 'Cultural note: the AH supermarket cake is fine but real Dutch people get proper cakes from the bakkerij for special occasions.' },
    ],
  },
  {
    id: 'vakantie-plannen',
    title: 'Holiday Plans',
    dutchTitle: 'Vakantieplannen',
    emoji: '✈️',
    description: 'Dutch colleagues comparing summer escapes from Dutch weather',
    level: 'A2',
    context: 'Het is dinsdag. Buiten regent het. Binnen praten Inge en Wouter over hun vakantieplannen alsof hun leven ervan afhangt.',
    speakers: { A: 'Inge', B: 'Wouter' },
    lines: [
      { speaker: 'A', dutch: 'Wouter. Zeg me dat jij ook al aan vakantie denkt.', english: 'Wouter. Tell me you\'re also already thinking about holidays.' },
      { speaker: 'B', dutch: 'Elke dag. Portugal in augustus.', english: 'Every day. Portugal in August.' },
      { speaker: 'A', dutch: 'Wauw. En wij gaan naar Toscane. Voor het eerst.', english: 'Wow. And we\'re going to Tuscany. For the first time.' },
      { speaker: 'B', dutch: 'Eerste keer Toscane?! Je gaat het geweldig vinden.', english: 'First time Tuscany?! You\'re going to love it.' },
      { speaker: 'A', dutch: 'Ik kijk er enorm naar uit. Zon. Warmte. Eten.', english: 'I\'m really looking forward to it. Sun. Warmth. Food.' },
      { speaker: 'B', dutch: 'Het eten alleen al. Dat maakt alles goed.', english: 'The food alone. That makes everything worthwhile.' },
      { speaker: 'A', dutch: 'Precies. En ik ga twee weken niksen. Geen laptop, geen Teams.', english: 'Exactly. And I\'m going to do absolutely nothing for two weeks. No laptop, no Teams.' },
      { speaker: 'B', dutch: 'Klinkt heerlijk. Wij ook. Huisje aan zee, geen wekker.', english: 'Sounds wonderful. Us too. Little house by the sea, no alarm.' },
      { speaker: 'A', dutch: 'Dat gun ik je echt.', english: 'You really deserve that.' },
      { speaker: 'B', dutch: 'Jij ook! Hoeveel dagen nog?', english: 'You too! How many days left?' },
      { speaker: 'A', dutch: 'Achtenveertig.', english: 'Forty-eight.' },
      { speaker: 'B', dutch: 'Je telt af.', english: 'You\'re counting down.' },
      { speaker: 'A', dutch: 'Elke ochtend.', english: 'Every morning.' },
    ],
    expressions: [
      { dutch: 'Ik kijk er enorm naar uit', english: 'I\'m really looking forward to it', note: '"Ergens naar uitkijken" = to look forward to something. "Enorm" = enormously. One of the best feelings to express in Dutch.' },
      { dutch: 'Het eten alleen al', english: 'The food alone (makes it worth it)', note: '"Alleen al" = alone/just. Implies something is SO good it justifies the whole thing by itself.' },
      { dutch: 'Niksen', english: 'Doing absolutely nothing on purpose', note: 'A Dutch word the whole world discovered. "Niksen" = deliberate, guilt-free doing of nothing. A skill, not laziness.' },
      { dutch: 'Dat gun ik je', english: 'You deserve that / I\'m genuinely happy for you', note: '"Gunnen" = to not begrudge someone something; to wish them well. One of the warmest Dutch words.' },
      { dutch: 'Aftellen', english: 'To count down', note: '"Aftellen" = to count down. "Je telt af" = you\'re counting down. The Dutch nod knowingly — they all do it.' },
      { dutch: 'Geen wekker', english: 'No alarm clock', note: 'The ultimate symbol of holiday freedom. Two of the best Dutch words together. Treasure them.' },
    ],
  },
]

export function getRealConversation(id: string): RealConversation | undefined {
  return realConversations.find((c) => c.id === id)
}

export function getRandomRealConversation(): RealConversation {
  return realConversations[Math.floor(Math.random() * realConversations.length)]
}
