export interface DialogueLine {
  speaker: 'A' | 'B'
  dutch: string
  english: string
}

export interface Expression {
  dutch: string
  english: string
  note: string
}

export interface RealConversation {
  id: string
  title: string
  dutchTitle: string
  emoji: string
  description: string
  level: 'A1' | 'A2' | 'B1'
  context: string
  speakers: { A: string; B: string }
  lines: DialogueLine[]
  expressions: Expression[]
}

export const realConversations: RealConversation[] = [
  {
    id: 'koffie-werk',
    title: 'Coffee at Work',
    dutchTitle: 'Koffie op het werk',
    emoji: '☕',
    description: 'Two colleagues chatting at the coffee machine',
    level: 'A2',
    context: 'Monday morning. Lars and Noor meet at the coffee machine in their Amsterdam office.',
    speakers: { A: 'Lars', B: 'Noor' },
    lines: [
      { speaker: 'A', dutch: 'Hé Noor, ook al zo vroeg?', english: 'Hey Noor, up this early too?' },
      { speaker: 'B', dutch: 'Joh, ik ben kapot. Het weekend was veel te kort.', english: 'Man, I\'m exhausted. The weekend was way too short.' },
      { speaker: 'A', dutch: 'Tell me about it. Heb je iets leuks gedaan?', english: 'Tell me about it. Did you do anything fun?' },
      { speaker: 'B', dutch: 'Beetje naar de markt geweest, verder niks bijzonders. Jij?', english: 'Went to the market a bit, nothing special otherwise. You?' },
      { speaker: 'A', dutch: 'Ach, gewoon thuis gehangen. Lekker lui.', english: 'Ah, just chilled at home. Nicely lazy.' },
      { speaker: 'B', dutch: 'Dat klinkt heerlijk eerlijk gezegd.', english: 'That sounds lovely honestly.' },
      { speaker: 'A', dutch: 'Zeg, heb jij die mail van Joost al gelezen?', english: 'Hey, have you read that email from Joost yet?' },
      { speaker: 'B', dutch: 'Nee, nog niet. Weer gedoe zeker?', english: 'No, not yet. More drama I assume?' },
      { speaker: 'A', dutch: 'Ja hoor, weer een extra vergadering vrijdagmiddag.', english: 'Yeah of course, another extra meeting Friday afternoon.' },
      { speaker: 'B', dutch: 'Serieus?! Op vrijdagmiddag?! Typisch.', english: 'Seriously?! On Friday afternoon?! Typical.' },
      { speaker: 'A', dutch: 'Ik weet het. Nou ja, eerst maar koffie.', english: 'I know. Well, coffee first.' },
      { speaker: 'B', dutch: 'Goed plan. Zonder koffie doe ik het niet.', english: 'Good plan. Without coffee I can\'t do it.' },
    ],
    expressions: [
      { dutch: 'Joh', english: 'Man / Wow / Jeez', note: 'Very common Dutch filler word, expresses mild surprise or emphasis. Like "man" in English.' },
      { dutch: 'Ik ben kapot', english: 'I\'m exhausted / dead tired', note: 'Literally "I am broken" — used to say you\'re very tired.' },
      { dutch: 'Niks bijzonders', english: 'Nothing special', note: 'Super common phrase when someone asks what you\'ve been up to.' },
      { dutch: 'Ach, gewoon', english: 'Ah, just / nothing much', note: '"Gewoon" is one of the most used Dutch words. "Ach, gewoon" = casual "not much".' },
      { dutch: 'Zeg', english: 'Hey / Say / Listen', note: 'Used to get someone\'s attention or introduce a new topic. Like "hey" or "listen" in English.' },
      { dutch: 'Weer gedoe', english: 'More drama / more hassle', note: '"Gedoe" means hassle, fuss, drama. "Weer gedoe" = here we go again.' },
      { dutch: 'Ja hoor', english: 'Yes indeed / Of course / Yep', note: 'Casual confirmation. Can also be sarcastic depending on tone.' },
      { dutch: 'Typisch', english: 'Typical / Of course (sarcastically)', note: 'Said when something annoying but predictable happens. Very Dutch.' },
      { dutch: 'Nou ja', english: 'Well / Oh well', note: 'Used to move on from something or accept a mildly frustrating situation.' },
    ],
  },
  {
    id: 'weekend-plannen',
    title: 'Weekend Plans',
    dutchTitle: 'Weekend plannen',
    emoji: '📅',
    description: 'Two friends making plans for the weekend',
    level: 'A1',
    context: 'Thursday evening. Emma and Daan are texting and then call each other about the weekend.',
    speakers: { A: 'Emma', B: 'Daan' },
    lines: [
      { speaker: 'A', dutch: 'Hé, wat doe jij dit weekend?', english: 'Hey, what are you doing this weekend?' },
      { speaker: 'B', dutch: 'Nog niks gepland eigenlijk. Hoezó?', english: 'Nothing planned yet actually. Why?' },
      { speaker: 'A', dutch: 'Ik wil zaterdag naar de bioscoop. Heb je zin?', english: 'I want to go to the cinema on Saturday. Are you up for it?' },
      { speaker: 'B', dutch: 'Ja leuk! Wat wil je zien dan?', english: 'Yeah nice! What do you want to see then?' },
      { speaker: 'A', dutch: 'Die nieuwe Marvel film. Schijnt super goed te zijn.', english: 'That new Marvel film. It\'s supposed to be really good.' },
      { speaker: 'B', dutch: 'Oh die! Ja die wil ik ook al een tijdje zien.', english: 'Oh that one! Yeah I\'ve wanted to see that for a while too.' },
      { speaker: 'A', dutch: 'Tof! Zullen we de avondfilm pakken? Om acht uur ofzo?', english: 'Cool! Shall we go for the evening showing? Around eight or so?' },
      { speaker: 'B', dutch: 'Prima. Eerst ergens eten?', english: 'Fine by me. Eat somewhere first?' },
      { speaker: 'A', dutch: 'Goed idee. Die nieuwe Thaise tent op de Overtoom?', english: 'Good idea. That new Thai place on Overtoom?' },
      { speaker: 'B', dutch: 'Oeh ja, die wil ik ook proberen. Top!', english: 'Ooh yes, I\'ve wanted to try that too. Great!' },
      { speaker: 'A', dutch: 'Oké, dan spreken we af om zeven uur bij jou?', english: 'Okay, so we\'ll meet at seven at yours?' },
      { speaker: 'B', dutch: 'Doe maar. Tot zaterdag!', english: 'Sure / Sounds good. See you Saturday!' },
    ],
    expressions: [
      { dutch: 'Hoezó?', english: 'Why? / How come?', note: 'A curious "why?" — not suspicious, just interested.' },
      { dutch: 'Heb je zin?', english: 'Are you up for it? / Do you fancy it?', note: '"Zin hebben" means to feel like doing something. Central to Dutch social invitations.' },
      { dutch: 'Schijnt ... te zijn', english: 'It\'s supposed to be / apparently it is', note: '"Schijnen" used this way means "apparently" or "reportedly".' },
      { dutch: 'Al een tijdje', english: 'For a while already', note: 'Common way to say you\'ve been wanting something for some time.' },
      { dutch: 'Tof', english: 'Cool / Great', note: 'Informal word for cool or great, widely used by younger Dutch speakers.' },
      { dutch: 'Ofzo', english: 'Or so / or something', note: 'Added to the end of suggestions to keep things casual and flexible.' },
      { dutch: 'Die nieuwe ... tent', english: 'That new ... place', note: '"Tent" informally means a place/restaurant/bar. Not rude — just casual.' },
      { dutch: 'Doe maar', english: 'Sure / Go ahead / Sounds good', note: 'One of the most Dutch phrases. Literally "just do it" — used to agree casually.' },
    ],
  },
  {
    id: 'trein-vertraging',
    title: 'Train Delay',
    dutchTitle: 'De trein heeft vertraging',
    emoji: '🚆',
    description: 'Commuters bonding over a delayed NS train',
    level: 'A2',
    context: 'A busy train platform. Fatima and Bas are both waiting for a delayed train.',
    speakers: { A: 'Fatima', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Alweer vertraging. Ik geloof er niks meer van.', english: 'Another delay. I don\'t believe it anymore.' },
      { speaker: 'B', dutch: 'Hoe laat had die moeten komen?', english: 'What time was it supposed to come?' },
      { speaker: 'A', dutch: 'Kwart over acht. Het is nu al half negen.', english: 'Quarter past eight. It\'s already half past eight now.' },
      { speaker: 'B', dutch: 'Toch te gek. En dan betaal je ook nog een vermogen voor zo\'n abonnement.', english: 'Absolutely ridiculous. And then you also pay a fortune for that subscription.' },
      { speaker: 'A', dutch: 'Precies! Ik word er echt knettergek van.', english: 'Exactly! It\'s genuinely driving me crazy.' },
      { speaker: 'B', dutch: 'Staat er wat op het bord? Ik zie niks.', english: 'Does the board say anything? I can\'t see anything.' },
      { speaker: 'A', dutch: 'Alleen "vertraging onbekend". Geweldig.', english: 'Only "delay unknown". Great.' },
      { speaker: 'B', dutch: 'Haha, klassiek NS. Kom je van ver?', english: 'Haha, classic NS. Do you come from far?' },
      { speaker: 'A', dutch: 'Nee, vanuit Leiden. Maar ik heb een vergadering om negen uur.', english: 'No, from Leiden. But I have a meeting at nine o\'clock.' },
      { speaker: 'B', dutch: 'Oef. Dat wordt krap. Misschien even een berichtje sturen?', english: 'Oef. That\'s going to be tight. Maybe send a quick message?' },
      { speaker: 'A', dutch: 'Ja, dat doe ik maar. Gelukkig begrijpt iedereen het tegenwoordig.', english: 'Yeah, I\'ll just do that. Luckily everyone understands nowadays.' },
      { speaker: 'B', dutch: 'Joh, NS is gewoon een nationale sport geworden, klagen over de trein.', english: 'Man, NS has just become a national sport, complaining about the train.' },
      { speaker: 'A', dutch: 'Haha, dat is echt zo!', english: 'Haha, that\'s so true!' },
    ],
    expressions: [
      { dutch: 'Ik geloof er niks meer van', english: 'I don\'t believe it anymore / I give up', note: 'Expressing total exasperation with a repeated situation.' },
      { dutch: 'Toch te gek', english: 'Absolutely ridiculous / unbelievable', note: '"Te gek" literally means "too crazy". Can be positive (amazingly cool) or negative (absolutely ridiculous) depending on context.' },
      { dutch: 'Een vermogen', english: 'A fortune', note: 'Literally "a fortune/wealth". Used to say something is very expensive.' },
      { dutch: 'Knettergek', english: 'Absolutely crazy / nuts', note: '"Knetter" is an intensifier in Dutch. "Knettergek worden van iets" = to be driven crazy by something.' },
      { dutch: 'Oef', english: 'Oef / oof / yikes', note: 'A sound expressing mild worry or sympathy. Very common in Dutch conversation.' },
      { dutch: 'Dat wordt krap', english: 'That\'s going to be tight', note: '"Krap" means tight/scarce. Used for time, money, or space.' },
      { dutch: 'Dat doe ik maar', english: 'I\'ll just do that', note: '"Maar" softens the action — "I\'ll just go ahead and do that".' },
      { dutch: 'Dat is echt zo', english: 'That\'s so true / that\'s really the case', note: 'Enthusiastic agreement in conversation.' },
    ],
  },
  {
    id: 'boodschappen-doen',
    title: 'Grocery Shopping',
    dutchTitle: 'Boodschappen doen',
    emoji: '🛍️',
    description: 'Housemates figuring out who does the shopping',
    level: 'A1',
    context: 'Sunday evening at home. Yara and Tim are housemates figuring out the weekly groceries.',
    speakers: { A: 'Yara', B: 'Tim' },
    lines: [
      { speaker: 'A', dutch: 'Tim, er is bijna niks meer in huis hoor.', english: 'Tim, there\'s barely anything left in the house.' },
      { speaker: 'B', dutch: 'Ja ik weet het, ik was het vergeten. Zullen we samen gaan?', english: 'Yeah I know, I forgot. Shall we go together?' },
      { speaker: 'A', dutch: 'Kan, maar ik heb eigenlijk geen zin. Lang dag gehad.', english: 'Could do, but I honestly don\'t feel like it. Had a long day.' },
      { speaker: 'B', dutch: 'Ik ga wel als jij een lijstje maakt?', english: 'I\'ll go if you make a list?' },
      { speaker: 'A', dutch: 'Deal. Wacht, ik check even de koelkast.', english: 'Deal. Wait, let me just check the fridge.' },
      { speaker: 'B', dutch: 'We hebben in ieder geval geen melk meer.', english: 'We don\'t have any milk left in any case.' },
      { speaker: 'A', dutch: 'En geen brood. Oh, en ik wil graag die Griekse yoghurt.', english: 'And no bread. Oh, and I really want that Greek yoghurt.' },
      { speaker: 'B', dutch: 'Die van Lidl of Albert Heijn?', english: 'The one from Lidl or Albert Heijn?' },
      { speaker: 'A', dutch: 'Lidl is goedkoper. Als je toch langskomt.', english: 'Lidl is cheaper. If you\'re passing by anyway.' },
      { speaker: 'B', dutch: 'Oké. Nog iets anders?', english: 'Okay. Anything else?' },
      { speaker: 'A', dutch: 'Hmm, pasta, tomatensaus en misschien wat fruit.', english: 'Hmm, pasta, tomato sauce and maybe some fruit.' },
      { speaker: 'B', dutch: 'Goed. Dan ga ik zo. Stuur jij het lijstje even?', english: 'Good. I\'ll go in a bit then. Will you just send me the list?' },
      { speaker: 'A', dutch: 'Doe ik. Je bent een schat!', english: 'Will do. You\'re a sweetheart!' },
    ],
    expressions: [
      { dutch: 'Er is bijna niks meer in huis', english: 'There\'s barely anything left in the house', note: 'Natural way to say the cupboards are almost empty.' },
      { dutch: 'Hoor', english: '(emphasis particle)', note: '"Hoor" at the end adds a gentle emphasis or heads-up tone. Hard to translate directly — makes the sentence feel more personal.' },
      { dutch: 'Eigenlijk geen zin', english: 'Honestly don\'t feel like it', note: '"Eigenlijk" = honestly/actually. "Geen zin hebben" = not feeling like doing something.' },
      { dutch: 'Lang dag gehad', english: 'Had a long day', note: 'Common Dutch shorthand — verb dropped, very conversational.' },
      { dutch: 'Even', english: 'Just / quickly', note: '"Even" is one of the most used Dutch words. It softens and quickens an action: "even checken" = just quickly check.' },
      { dutch: 'In ieder geval', english: 'In any case / at least', note: 'Used to state what you know for certain among uncertain things.' },
      { dutch: 'Als je toch langskomt', english: 'If you\'re passing by anyway', note: '"Toch" here means "anyway" — a very Dutch word that shifts the logic of a sentence.' },
      { dutch: 'Je bent een schat', english: 'You\'re a sweetheart / you\'re a gem', note: '"Schat" literally means treasure. A warm, common compliment.' },
    ],
  },
  {
    id: 'verjaardag-party',
    title: 'Birthday Plans',
    dutchTitle: 'Verjaardag plannen',
    emoji: '🎂',
    description: 'Friends organising a surprise birthday party',
    level: 'A2',
    context: 'Two friends, Roos and Joep, are calling to plan a surprise party for their friend Lotte.',
    speakers: { A: 'Roos', B: 'Joep' },
    lines: [
      { speaker: 'A', dutch: 'Joep, Lotte wordt volgende week zaterdag dertig. Doen we iets?', english: 'Joep, Lotte turns thirty next Saturday. Are we doing something?' },
      { speaker: 'B', dutch: 'Jaaaa dat was ik bijna vergeten! Goed dat jij eraan denkt.', english: 'Yaaa I almost forgot that! Good that you thought of it.' },
      { speaker: 'A', dutch: 'Zullen we een verrassingsfeestje doen? Ze weet van niks.', english: 'Shall we do a surprise party? She has no idea.' },
      { speaker: 'B', dutch: 'Oeh dat is leuk! Bij wie thuis dan?', english: 'Ooh that\'s fun! At whose place then?' },
      { speaker: 'A', dutch: 'Bij mij kan wel. Ik heb genoeg ruimte.', english: 'At mine is fine. I have enough space.' },
      { speaker: 'B', dutch: 'Top. Hoeveel mensen denk je?', english: 'Great. How many people are you thinking?' },
      { speaker: 'A', dutch: 'Niet te groot. Haar beste vrienden, twintig man ofzo.', english: 'Not too big. Her closest friends, about twenty people or so.' },
      { speaker: 'B', dutch: 'Goed. Ik regel wel de drank als jij het eten doet?', english: 'Good. I\'ll sort the drinks if you do the food?' },
      { speaker: 'A', dutch: 'Prima. Oh, en iemand moet haar erheen lokken.', english: 'Fine. Oh, and someone needs to lure her there.' },
      { speaker: 'B', dutch: 'Dat doet Sanne wel, die kan goed liegen.', english: 'Sanne can do that, she\'s a good liar.' },
      { speaker: 'A', dutch: 'Haha ja, ideaal! Oké ik maak een appje aan.', english: 'Haha yes, perfect! Okay I\'ll create a WhatsApp group.' },
      { speaker: 'B', dutch: 'Let op dat Lotte er niet in zit hè!', english: 'Make sure Lotte\'s not in it yeah!' },
      { speaker: 'A', dutch: 'Ja hallo, dat snap ik zelf ook wel!', english: 'Yeah come on, I know that myself!' },
    ],
    expressions: [
      { dutch: 'Ze weet van niks', english: 'She has no idea / she doesn\'t know anything about it', note: 'Common phrase for when someone is completely unaware of a plan.' },
      { dutch: 'Bij mij kan wel', english: 'At mine is fine / my place works', note: '"Kan wel" is a casual way to say something is possible/fine.' },
      { dutch: 'Ik regel wel', english: 'I\'ll sort it / I\'ll handle it', note: '"Regelen" = to arrange/sort. "Ik regel het wel" is a confident, casual offer to take care of something.' },
      { dutch: 'Iemand moet haar erheen lokken', english: 'Someone needs to lure her there', note: '"Lokken" = to lure/tempt. Used when you need to get someone somewhere without them knowing why.' },
      { dutch: 'Ideaal', english: 'Perfect / ideal', note: 'Used very casually in Dutch to mean "perfect" or "that works great".' },
      { dutch: 'Een appje aanmaken', english: 'Create a WhatsApp group', note: '"Appje" = WhatsApp message/group (informal). Central to Dutch social life.' },
      { dutch: 'Let op', english: 'Watch out / make sure / pay attention', note: '"Let op" is used to give a heads-up or warning.' },
      { dutch: 'Ja hallo', english: 'Come on / obviously / yeah duh', note: 'Used when you think something is obvious. Mild, not rude — like "come on now".' },
    ],
  },
  {
    id: 'weer-klagen',
    title: 'Complaining About the Weather',
    dutchTitle: 'Over het weer klagen',
    emoji: '🌧️',
    description: 'A very Dutch conversation about the terrible weather',
    level: 'A1',
    context: 'Two neighbours, Henk and Marjolein, meet outside on a grey, drizzly Dutch morning.',
    speakers: { A: 'Henk', B: 'Marjolein' },
    lines: [
      { speaker: 'A', dutch: 'Goedemorgen! Wat een weer, hè?', english: 'Good morning! What weather, huh?' },
      { speaker: 'B', dutch: 'Hè ja, vreselijk. Alweer regen.', english: 'Yeah, terrible. Rain again.' },
      { speaker: 'A', dutch: 'Het heeft de hele week al geregend. Ik word er somber van.', english: 'It\'s been raining all week. It\'s making me gloomy.' },
      { speaker: 'B', dutch: 'Wacht maar, ze zeggen dat het weekend beter wordt.', english: 'Just wait, they say the weekend will be better.' },
      { speaker: 'A', dutch: 'Dat zeggen ze altijd. Ik geloof de buienradar allang niet meer.', english: 'They always say that. I stopped trusting the weather app long ago.' },
      { speaker: 'B', dutch: 'Haha, ik ook niet. Maar goed, wat wil je, het is Nederland.', english: 'Haha, me neither. But well, what do you expect, it\'s the Netherlands.' },
      { speaker: 'A', dutch: 'Zo is dat. Ik ga mijn paraplu maar meenemen.', english: 'That\'s right. I\'ll just take my umbrella then.' },
      { speaker: 'B', dutch: 'Doe dat. En een extra jas, voor de zekerheid.', english: 'Do that. And an extra jacket, just to be sure.' },
      { speaker: 'A', dutch: 'Altijd. Nou, fijne dag verder hoor!', english: 'Always. Well, have a good rest of your day!' },
      { speaker: 'B', dutch: 'Jij ook! En hou je droog!', english: 'You too! And stay dry!' },
    ],
    expressions: [
      { dutch: 'Wat een weer, hè?', english: 'What weather, huh?', note: 'The most Dutch opener possible. A safe, universal conversation starter.' },
      { dutch: 'Ik word er somber van', english: 'It makes me gloomy / it brings me down', note: '"Somber worden van iets" = to be made gloomy/depressed by something.' },
      { dutch: 'Wacht maar', english: 'Just wait / you\'ll see', note: 'Used to reassure or predict — "just wait and see".' },
      { dutch: 'Allang niet meer', english: 'Haven\'t for a long time / stopped long ago', note: '"Allang" = for a long time already. "Allang niet meer" = not anymore for a long time.' },
      { dutch: 'Maar goed, wat wil je', english: 'But well, what do you expect', note: 'A very Dutch expression of resignation — accepting that things are the way they are.' },
      { dutch: 'Zo is dat', english: 'That\'s right / that\'s how it is', note: 'Used to agree with or confirm a statement.' },
      { dutch: 'Voor de zekerheid', english: 'Just to be sure / as a precaution', note: 'Extremely common Dutch phrase when taking precautions.' },
      { dutch: 'Hou je droog', english: 'Stay dry', note: 'A very Dutch farewell, especially in autumn and winter.' },
    ],
  },
  {
    id: 'ajax-voetbal',
    title: 'Talking Football',
    dutchTitle: 'Over voetbal praten',
    emoji: '⚽',
    description: 'Two friends discussing Ajax after a match',
    level: 'A2',
    context: 'Sunday evening. Milan and Stef are calling each other after watching Ajax play.',
    speakers: { A: 'Milan', B: 'Stef' },
    lines: [
      { speaker: 'A', dutch: 'Heb je de wedstrijd gezien? Wat een drama!', english: 'Did you watch the match? What a disaster!' },
      { speaker: 'B', dutch: 'Joh, ik ben er nog steeds boos over. Hoe kun je dat nou weggeven?', english: 'Man, I\'m still angry about it. How can you just throw that away?' },
      { speaker: 'A', dutch: 'Die keeper stond echt te slapen. Drie goals doorgegeven, ongelooflijk.', english: 'That goalkeeper was literally sleeping. Let in three goals, unbelievable.' },
      { speaker: 'B', dutch: 'En die scheidsrechter! Die floot voor van alles en nog wat.', english: 'And that referee! He was blowing his whistle for everything and anything.' },
      { speaker: 'A', dutch: 'Laat me niet lachen. We hadden gewoon moeten winnen.', english: 'Don\'t make me laugh. We simply should have won.' },
      { speaker: 'B', dutch: 'Precies. De eerste helft was nog oké maar daarna ging het helemaal mis.', english: 'Exactly. The first half was still okay but after that it all went wrong.' },
      { speaker: 'A', dutch: 'Ik snap de opstelling ook niet. Waarom speelde Brobbey niet?', english: 'I don\'t understand the line-up either. Why wasn\'t Brobbey playing?' },
      { speaker: 'B', dutch: 'Geen idee. De trainer maakt er ook een potje van.', english: 'No idea. The coach is making a mess of it too.' },
      { speaker: 'A', dutch: 'Ach, volgend seizoen wordt het beter. Dat zeg ik al tien jaar.', english: 'Ah well, next season will be better. I\'ve been saying that for ten years.' },
      { speaker: 'B', dutch: 'Haha toch? Maar we blijven kijken, of niet soms?', english: 'Haha right? But we keep watching, don\'t we?' },
      { speaker: 'A', dutch: 'Natuurlijk. Eenmaal Ajax-fan, altijd Ajax-fan.', english: 'Of course. Once an Ajax fan, always an Ajax fan.' },
    ],
    expressions: [
      { dutch: 'Wat een drama', english: 'What a disaster / what a mess', note: '"Drama" in Dutch is used casually for anything that went badly.' },
      { dutch: 'Hoe kun je dat nou weggeven?', english: 'How can you just throw that away?', note: '"Weggeven" in sports = to give away a goal/lead.' },
      { dutch: 'Voor van alles en nog wat', english: 'For everything and anything / for the slightest thing', note: 'Means someone reacts to absolutely everything.' },
      { dutch: 'Laat me niet lachen', english: 'Don\'t make me laugh / give me a break', note: 'Expression of disbelief or dismissal. Not always literally about laughing.' },
      { dutch: 'Daarna ging het helemaal mis', english: 'After that it all went wrong', note: '"Helemaal mis gaan" = to go completely wrong.' },
      { dutch: 'Een potje van maken', english: 'To make a mess of it', note: '"Een potje maken van iets" = to make a total mess of something.' },
      { dutch: 'Of niet soms?', english: 'Don\'t we? / right?', note: 'A tag question seeking agreement. Very common in spoken Dutch.' },
    ],
  },
  {
    id: 'huisgenoten-klusjes',
    title: 'Housemate Chores',
    dutchTitle: 'Huishoudelijke klusjes',
    emoji: '🧹',
    description: 'Housemates negotiating who does what',
    level: 'A2',
    context: 'Studenthouse in Utrecht. Lena and Thomas are having their weekly "who does what" conversation.',
    speakers: { A: 'Lena', B: 'Thomas' },
    lines: [
      { speaker: 'A', dutch: 'Thomas, de keuken is echt een puinhoop. Wie was er aan de beurt?', english: 'Thomas, the kitchen is a real mess. Whose turn was it?' },
      { speaker: 'B', dutch: 'O nee, dat was ik. Sorry, ik had het echt druk deze week.', english: 'Oh no, that was me. Sorry, I was genuinely busy this week.' },
      { speaker: 'A', dutch: 'Oké maar het kan zo echt niet. De vaat staat er al twee dagen in.', english: 'Okay but it can\'t stay like this. The dishes have been there for two days.' },
      { speaker: 'B', dutch: 'Ik doe het nu meteen, beloofd. Doe jij dan de badkamer?', english: 'I\'ll do it right now, I promise. Will you do the bathroom then?' },
      { speaker: 'A', dutch: 'Ik heb de badkamer vorige week ook al gedaan hoor.', english: 'I already did the bathroom last week too you know.' },
      { speaker: 'B', dutch: 'Ja maar ik doe de keuken en het aanrecht én de vloer, is dat goed?', english: 'Yeah but I\'ll do the kitchen and the counter AND the floor, is that okay?' },
      { speaker: 'A', dutch: 'Hmm, oké dan. Maar dan doe jij volgende week ook de badkamer.', english: 'Hmm, okay then. But then you\'re doing the bathroom next week too.' },
      { speaker: 'B', dutch: 'Deal. En misschien moeten we een poetsrooster maken?', english: 'Deal. And maybe we should make a cleaning schedule?' },
      { speaker: 'A', dutch: 'Goed idee, had ik al vaker gezegd.', english: 'Good idea, I\'ve said that before many times.' },
      { speaker: 'B', dutch: 'Ja ja, je had gelijk. Ik geef het toe.', english: 'Yeah yeah, you were right. I admit it.' },
      { speaker: 'A', dutch: 'Fijn. Nu nog zorgen dat iedereen zich eraan houdt.', english: 'Good. Now we just need to make sure everyone sticks to it.' },
    ],
    expressions: [
      { dutch: 'Een puinhoop', english: 'A complete mess', note: '"Puinhoop" literally means rubble/ruins. Used informally for any messy situation.' },
      { dutch: 'Aan de beurt zijn', english: 'To be someone\'s turn', note: '"Aan de beurt zijn" = to be the one whose turn it is. Essential for housemate life.' },
      { dutch: 'Het had ik echt druk', english: 'I was genuinely busy', note: '"Druk hebben" = to be busy. "Echt druk" emphasises it.' },
      { dutch: 'Dat kan zo echt niet', english: 'It can\'t stay like this / this is not okay', note: 'A gentle but firm way to say a situation is unacceptable.' },
      { dutch: 'Nu meteen', english: 'Right now / immediately', note: '"Nu meteen" is more urgent than just "nu" — it means right this instant.' },
      { dutch: 'Beloofd', english: 'I promise', note: 'Simply the past participle of "beloven" used as a standalone promise.' },
      { dutch: 'Ik geef het toe', english: 'I admit it', note: '"Toegeven" = to admit/concede. "Ik geef het toe" = I admit it.' },
      { dutch: 'Zich eraan houden', english: 'To stick to it / to follow through', note: '"Zich ergens aan houden" = to keep to something/stick to an agreement.' },
    ],
  },
  {
    id: 'nieuwe-baan',
    title: 'New Job',
    dutchTitle: 'Nieuwe baan',
    emoji: '🎉',
    description: 'A friend shares exciting news about a new job',
    level: 'A2',
    context: 'Two old friends, Sophie and Rick, catch up over the phone.',
    speakers: { A: 'Sophie', B: 'Rick' },
    lines: [
      { speaker: 'A', dutch: 'Rick! Ik heb nieuws. Ik heb een nieuwe baan!', english: 'Rick! I have news. I got a new job!' },
      { speaker: 'B', dutch: 'Wat?! Echt?! Gefeliciteerd! Vertel!', english: 'What?! Really?! Congratulations! Tell me!' },
      { speaker: 'A', dutch: 'Bij een tech startup in Amsterdam. Ik begin volgende maand.', english: 'At a tech startup in Amsterdam. I start next month.' },
      { speaker: 'B', dutch: 'Wauw, dat is gaaf! Hoe ben je daar terecht gekomen?', english: 'Wow, that\'s cool! How did you end up there?' },
      { speaker: 'A', dutch: 'Via LinkedIn. Ze kwamen zelf naar mij toe, hoe gek is dat.', english: 'Via LinkedIn. They came to me themselves, how crazy is that.' },
      { speaker: 'B', dutch: 'Dat is helemaal niet gek, jij bent gewoon goed!', english: 'That\'s not crazy at all, you\'re just good!' },
      { speaker: 'A', dutch: 'Haha, doe normaal. Maar ik ben wel heel blij.', english: 'Haha, stop it. But I am really happy.' },
      { speaker: 'B', dutch: 'Terecht! Wat ga je precies doen?', english: 'Rightly so! What will you be doing exactly?' },
      { speaker: 'A', dutch: 'UX design. Mijn drooombaan eigenlijk.', english: 'UX design. My dream job really.' },
      { speaker: 'B', dutch: 'Dat meen je niet! Daar heb je het altijd over gehad.', english: 'You\'re joking! You\'ve always talked about that.' },
      { speaker: 'A', dutch: 'Ik weet het. Het voelt nog een beetje onwerkelijk.', english: 'I know. It still feels a bit unreal.' },
      { speaker: 'B', dutch: 'Goed verdiend, echt. We moeten dit vieren. Vanavond een biertje?', english: 'Well deserved, really. We need to celebrate this. A beer tonight?' },
      { speaker: 'A', dutch: 'Ja man, dat lijkt me top!', english: 'Yes mate, that sounds great!' },
    ],
    expressions: [
      { dutch: 'Vertel!', english: 'Tell me! / Go on!', note: 'A one-word enthusiastic invitation to share more. Very natural in excited conversation.' },
      { dutch: 'Hoe ben je daar terecht gekomen?', english: 'How did you end up there?', note: '"Terechtkomen bij" = to end up at a place/company.' },
      { dutch: 'Hoe gek is dat', english: 'How crazy is that / isn\'t that wild', note: 'Said with wonder or surprise, not necessarily negative.' },
      { dutch: 'Doe normaal', english: 'Stop it / come off it / be normal', note: 'Literally "be normal". Used to brush off a compliment or to tell someone to calm down. Very Dutch.' },
      { dutch: 'Terecht', english: 'Rightly so / deservedly', note: '"Terecht" validates or confirms that something is fair/deserved.' },
      { dutch: 'Dat meen je niet', english: 'You\'re joking / no way', note: '"Menen" = to mean/intend. "Dat meen je niet!" = You can\'t be serious!' },
      { dutch: 'Onwerkelijk', english: 'Unreal / surreal', note: 'Used when something feels too good or too strange to be true.' },
      { dutch: 'Goed verdiend', english: 'Well deserved', note: 'A warm compliment acknowledging someone earned their success.' },
    ],
  },
  {
    id: 'ziek-thuis',
    title: 'Calling in Sick',
    dutchTitle: 'Ziek thuis',
    emoji: '🤒',
    description: 'Calling your boss to say you\'re not coming in',
    level: 'A2',
    context: 'Mia wakes up feeling terrible and calls her manager Kevin to say she can\'t come in.',
    speakers: { A: 'Mia', B: 'Kevin' },
    lines: [
      { speaker: 'A', dutch: 'Hallo Kevin, met Mia. Ik bel om te zeggen dat ik me niet goed voel.', english: 'Hello Kevin, this is Mia. I\'m calling to say I\'m not feeling well.' },
      { speaker: 'B', dutch: 'Oh, wat is er aan de hand?', english: 'Oh, what\'s the matter?' },
      { speaker: 'A', dutch: 'Keelpijn, hoofdpijn en ik heb koorts. Ik denk dat ik grip heb.', english: 'Sore throat, headache and I have a fever. I think I have the flu.' },
      { speaker: 'B', dutch: 'Dat klinkt niet goed. Dan moet je gewoon thuisblijven.', english: 'That doesn\'t sound good. Then you should just stay home.' },
      { speaker: 'A', dutch: 'Ja, ik vind het vervelend, want we hebben die deadline deze week.', english: 'Yes, I feel bad about it, because we have that deadline this week.' },
      { speaker: 'B', dutch: 'Maak je daar maar geen zorgen over. Je gezondheid gaat voor.', english: 'Don\'t worry about that. Your health comes first.' },
      { speaker: 'A', dutch: 'Dankjewel. Ik zal de stukken wel doorsturen naar Pieter.', english: 'Thank you. I\'ll forward the documents to Pieter.' },
      { speaker: 'B', dutch: 'Dat hoeft niet meteen, rust eerst maar uit.', english: 'You don\'t have to do that right away, just rest first.' },
      { speaker: 'A', dutch: 'Oké. Ik laat het weten als ik morgen ook niet kan komen.', english: 'Okay. I\'ll let you know if I can\'t come in tomorrow either.' },
      { speaker: 'B', dutch: 'Prima. Beterschap, Mia!', english: 'That\'s fine. Get well soon, Mia!' },
      { speaker: 'A', dutch: 'Bedankt. Tot snel hopelijk.', english: 'Thank you. Hopefully see you soon.' },
    ],
    expressions: [
      { dutch: 'Met [naam]', english: '[name] speaking / this is [name]', note: 'How Dutch people answer or introduce themselves on the phone. Always "Met Mia", not "Ik ben Mia".' },
      { dutch: 'Wat is er aan de hand?', english: 'What\'s the matter? / What\'s going on?', note: 'Friendly way to ask what the problem is.' },
      { dutch: 'Ik vind het vervelend', english: 'I feel bad about it / I\'m sorry about it', note: '"Vervelend vinden" = to find something annoying or to feel sorry/bad about it.' },
      { dutch: 'Je gezondheid gaat voor', english: 'Your health comes first', note: 'A reassuring phrase — health takes priority over work.' },
      { dutch: 'Dat hoeft niet meteen', english: 'You don\'t have to do that right away', note: '"Hoeven" is the key verb here — "need to/have to" in negative/question contexts.' },
      { dutch: 'Uitrusten', english: 'To rest up', note: '"Rust uit" or "uitrusten" — to rest and recover.' },
      { dutch: 'Ik laat het weten', english: 'I\'ll let you know', note: 'Essential phrase for any update situation.' },
      { dutch: 'Beterschap!', english: 'Get well soon!', note: 'THE Dutch phrase when someone is sick. Always use this instead of "get well soon".' },
    ],
  },
  {
    id: 'huurhuis-zoeken',
    title: 'Finding a Flat',
    dutchTitle: 'Een huurhuis zoeken',
    emoji: '🏠',
    description: 'Two expats discussing the Dutch housing nightmare',
    level: 'B1',
    context: 'Two colleagues, both living in Amsterdam, talking about the impossible housing market.',
    speakers: { A: 'Ana', B: 'Sven' },
    lines: [
      { speaker: 'A', dutch: 'Sven, ik ben al drie maanden aan het zoeken naar een woning. Ik word er gek van.', english: 'Sven, I\'ve been looking for a home for three months. I\'m going crazy.' },
      { speaker: 'B', dutch: 'Ik snap het. Amsterdam is gewoon onmogelijk. Hoe hoog is je budget?', english: 'I understand. Amsterdam is just impossible. What\'s your budget?' },
      { speaker: 'A', dutch: 'Tot 1500 euro per maand. Maar voor dat geld krijg je bijna niks.', english: 'Up to 1500 euros per month. But for that price you get almost nothing.' },
      { speaker: 'B', dutch: 'Helaas klopt dat. Heb je Funda al geprobeerd?', english: 'Unfortunately that\'s true. Have you tried Funda already?' },
      { speaker: 'A', dutch: 'Funda, Pararius, alles. Zodra er iets bijkomt is het al weg.', english: 'Funda, Pararius, everything. As soon as something comes up it\'s already gone.' },
      { speaker: 'B', dutch: 'Heb je ook gekeken buiten Amsterdam? Haarlem of Amstelveen ofzo?', english: 'Have you also looked outside Amsterdam? Haarlem or Amstelveen or something?' },
      { speaker: 'A', dutch: 'Ja, maar dan wordt het woon-werkverkeer een stuk zwaarder.', english: 'Yeah, but then the commute becomes much harder.' },
      { speaker: 'B', dutch: 'Dat begrijp ik. Ken je iemand bij een woningcorporatie?', english: 'I understand that. Do you know anyone at a housing association?' },
      { speaker: 'A', dutch: 'Nee. En de sociale huurwachtlijst is zeven jaar, heb ik gehoord.', english: 'No. And the social housing waiting list is seven years, I\'ve heard.' },
      { speaker: 'B', dutch: 'Zeven jaar?! Dat is toch te waanzinnig voor woorden.', english: 'Seven years?! That\'s absolutely insane.' },
      { speaker: 'A', dutch: 'Welkom in Nederland.', english: 'Welcome to the Netherlands.' },
      { speaker: 'B', dutch: 'Haha, helaas. Ik hoor het als ik iets hoor.', english: 'Haha, unfortunately. I\'ll let you know if I hear anything.' },
    ],
    expressions: [
      { dutch: 'Ik word er gek van', english: 'I\'m going crazy from it / it\'s driving me insane', note: 'Strong expression of frustration with an ongoing situation.' },
      { dutch: 'Voor dat geld krijg je bijna niks', english: 'For that money you get almost nothing', note: 'Sadly very common in Dutch housing conversations.' },
      { dutch: 'Zodra er iets bijkomt is het al weg', english: 'As soon as something comes up it\'s already gone', note: '"Bijkomen" = to come up/be added. Describes the speed of the housing market.' },
      { dutch: 'Een stuk zwaarder', english: 'A lot harder / significantly heavier', note: '"Een stuk" = a lot/considerably (informal intensifier).' },
      { dutch: 'Te waanzinnig voor woorden', english: 'Too crazy for words / absolutely insane', note: '"Te [adj] voor woorden" = beyond description. Strong expression of disbelief.' },
      { dutch: 'Welkom in Nederland', english: 'Welcome to the Netherlands', note: 'Sarcastic phrase used when something typically Dutch and frustrating is accepted as normal.' },
      { dutch: 'Ik hoor het als ik iets hoor', english: 'I\'ll let you know if I hear anything', note: 'Literally "I\'ll hear it when I hear something." A common way to promise to pass on information.' },
    ],
  },
  {
    id: 'sinterklaas',
    title: 'Sinterklaas',
    dutchTitle: 'Sinterklaas vieren',
    emoji: '🎅',
    description: 'Family preparing for Sinterklaas evening',
    level: 'A2',
    context: 'December 5th. Mum Ellen and dad Paul are getting ready for Sinterklaas with the kids.',
    speakers: { A: 'Ellen', B: 'Paul' },
    lines: [
      { speaker: 'A', dutch: 'Paul, heb jij de surprises al klaar?', english: 'Paul, do you have the surprises ready already?' },
      { speaker: 'B', dutch: 'Bijna. Ik moet alleen nog inpakken. Hoe laat komen ze?', english: 'Almost. I just need to wrap them up. What time are they coming?' },
      { speaker: 'A', dutch: 'Rond half zes. En de kinderen weten nog van niks, toch?', english: 'Around half five. And the kids still don\'t know anything, right?' },
      { speaker: 'B', dutch: 'Nee hoor. Oh trouwens, heb jij de gedichten al gelezen?', english: 'No no. Oh by the way, have you read the poems already?' },
      { speaker: 'A', dutch: 'Nog niet. Zijn ze goed?', english: 'Not yet. Are they good?' },
      { speaker: 'B', dutch: 'Die van Lisa is hilarisch. Ze heeft de hele familie op de hak genomen.', english: 'Lisa\'s is hilarious. She\'s made fun of the whole family.' },
      { speaker: 'A', dutch: 'Haha! Dat klinkt als Lisa. Ze gaat toch niet te ver?', english: 'Haha! That sounds like Lisa. She\'s not going too far though?' },
      { speaker: 'B', dutch: 'Nee nee, het is allemaal goed bedoeld. Heel grappig.', english: 'No no, it\'s all well-intentioned. Very funny.' },
      { speaker: 'A', dutch: 'Mooi. Heb jij nog pepernoten gekocht?', english: 'Good. Did you buy pepernoten?' },
      { speaker: 'B', dutch: 'Een hele zak! En speculaas.', english: 'A whole bag! And speculaas.' },
      { speaker: 'A', dutch: 'Top. Ik ga alvast chocolademelk maken voor de kinderen.', english: 'Great. I\'ll make hot chocolate for the kids in advance.' },
      { speaker: 'B', dutch: 'Lekker. Wordt toch wel een gezellige avond!', english: 'Nice. It\'s going to be a cosy evening!' },
    ],
    expressions: [
      { dutch: 'Ze weten nog van niks', english: 'They still don\'t know anything about it', note: 'Used when keeping a surprise — no one has spilled the beans.' },
      { dutch: 'Trouwens', english: 'By the way / anyway', note: 'Used to introduce a new, related thought. Like "by the way" or "oh, and also".' },
      { dutch: 'Op de hak nemen', english: 'To poke fun at / to tease', note: 'Sinterklaas poems traditionally tease the recipient. "Op de hak nemen" = to make fun of affectionately.' },
      { dutch: 'Goed bedoeld', english: 'Well-intentioned / meant well', note: '"Goed bedoelen" = to mean well. Assurance that teasing is friendly.' },
      { dutch: 'Mooi', english: 'Good / nice / great', note: '"Mooi" doesn\'t just mean beautiful — used as a casual "great" or "good" in conversation.' },
      { dutch: 'Alvast', english: 'Already / in advance', note: '"Alvast" means doing something ahead of time or before something else happens.' },
      { dutch: 'Gezellig', english: 'Cosy / fun / convivial / nice', note: 'THE most Dutch word. No exact English translation — warmth, togetherness, and cosiness combined.' },
    ],
  },
  {
    id: 'fiets-gestolen',
    title: 'Stolen Bike',
    dutchTitle: 'Fiets gestolen',
    emoji: '😤',
    description: 'A very Dutch crisis: your bike got stolen',
    level: 'A2',
    context: 'Nadia just discovered her bike is gone and calls her friend Bas.',
    speakers: { A: 'Nadia', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Bas, ze hebben mijn fiets gestolen!!', english: 'Bas, they stole my bike!!' },
      { speaker: 'B', dutch: 'Nee toch?! Waar stond ie dan?', english: 'No way?! Where was it then?' },
      { speaker: 'A', dutch: 'Gewoon voor de deur. Met een goed slot ook!', english: 'Just in front of the door. With a good lock too!' },
      { speaker: 'B', dutch: 'Joh, die dieven zijn nergens voor teruggeschrokken in Amsterdam.', english: 'Man, those thieves stop at nothing in Amsterdam.' },
      { speaker: 'A', dutch: 'Ik ben zo kwaad. Het was mijn nieuwe fiets nog wel.', english: 'I\'m so angry. And it was my new bike too.' },
      { speaker: 'B', dutch: 'Heb je aangifte gedaan bij de politie?', english: 'Have you filed a report with the police?' },
      { speaker: 'A', dutch: 'Ja, maar die zeiden al dat de kans klein is dat ze hem terugvinden.', english: 'Yes, but they already said the chance of finding it is small.' },
      { speaker: 'B', dutch: 'Dat snap ik. En je verzekering?', english: 'I get that. And your insurance?' },
      { speaker: 'A', dutch: 'Die dekt het gelukkig wel. Maar ik moet nu eerst een nieuwe kopen.', english: 'Fortunately that covers it. But I need to buy a new one first now.' },
      { speaker: 'B', dutch: 'Als je wilt kun je mijn reservefiets even lenen.', english: 'If you want you can borrow my spare bike for a while.' },
      { speaker: 'A', dutch: 'Oh dat is super lief van je! Dan zijn we gered.', english: 'Oh that\'s super sweet of you! Then we\'re saved.' },
      { speaker: 'B', dutch: 'Tuurlijk. En koop dit keer twee sloten.', english: 'Of course. And buy two locks this time.' },
      { speaker: 'A', dutch: 'Haha, dat beloof ik.', english: 'Haha, I promise.' },
    ],
    expressions: [
      { dutch: 'Nee toch?!', english: 'No way?! / You\'re kidding?!', note: 'Disbelief expression. "Toch" here intensifies the shock.' },
      { dutch: 'Gewoon voor de deur', english: 'Right in front of the door', note: '"Gewoon" here = simply/just. Adds to the frustration of the ordinary location.' },
      { dutch: 'Nergens voor terugschrikken', english: 'To stop at nothing', note: 'Literally "scared of nothing". Used to say someone is bold/shameless.' },
      { dutch: 'Zo kwaad', english: 'So angry', note: '"Kwaad" = angry (not "bad"). "Zo kwaad zijn" = to be so angry.' },
      { dutch: 'Nog wel', english: '... and it was ... too / of all things', note: '"Nog wel" emphasises that it makes the situation even more frustrating.' },
      { dutch: 'Aangifte doen', english: 'To file a police report', note: 'Essential phrase for any crime — you "do aangifte" at the police.' },
      { dutch: 'Dan zijn we gered', english: 'Then we\'re saved', note: 'Melodramatic but common — expresses relief that a problem is solved.' },
      { dutch: 'Tuurlijk', english: 'Of course', note: 'Casual version of "natuurlijk". Very common in spoken Dutch.' },
    ],
  },
  {
    id: 'etentje-organiseren',
    title: 'Organising Dinner',
    dutchTitle: 'Etentje organiseren',
    emoji: '🍷',
    description: 'Planning a dinner party with friends',
    level: 'A2',
    context: 'Two friends, Fleur and Diederik, are planning a dinner party for six people.',
    speakers: { A: 'Fleur', B: 'Diederik' },
    lines: [
      { speaker: 'A', dutch: 'Diederik, we moeten binnenkort een etentje doen.', english: 'Diederik, we need to do a dinner soon.' },
      { speaker: 'B', dutch: 'Helemaal mee eens. Bij jou of bij mij?', english: 'Totally agree. At yours or at mine?' },
      { speaker: 'A', dutch: 'Bij mij kan prima. Ik kook graag. Met hoeveel mensen denk je?', english: 'At mine is fine. I love cooking. How many people are you thinking?' },
      { speaker: 'B', dutch: 'Zes, acht mensen misschien? Niet te groot.', english: 'Six, eight people maybe? Not too big.' },
      { speaker: 'A', dutch: 'Goed. Ik maak een groepje aan. Welk weekend werkt voor jou?', english: 'Good. I\'ll create a group. Which weekend works for you?' },
      { speaker: 'B', dutch: 'Niet dit weekend maar daarna. Over twee weken?', english: 'Not this weekend but the next one. In two weeks?' },
      { speaker: 'A', dutch: 'Dat moet lukken. Wat zal ik maken? Ik ben aan het twijfelen.', english: 'That should work. What shall I make? I\'m torn.' },
      { speaker: 'B', dutch: 'Doe maar gewoon iets lekkers. Pasta of zo.', english: 'Just make something tasty. Pasta or something.' },
      { speaker: 'A', dutch: 'Iemand met dieetwensen weet je?', english: 'Anyone with dietary requirements do you know?' },
      { speaker: 'B', dutch: 'Lars eet geen vlees. En Nina is lactose-intolerant, geloof ik.', english: 'Lars doesn\'t eat meat. And Nina is lactose intolerant, I think.' },
      { speaker: 'A', dutch: 'Oké, dan houd ik daar rekening mee. Iedereen brengt een fles wijn mee?', english: 'Okay, I\'ll take that into account. Everyone brings a bottle of wine?' },
      { speaker: 'B', dutch: 'Ja, en ik neem een toetje mee. Ik kan best lekker bakken.', english: 'Yes, and I\'ll bring a dessert. I\'m actually quite good at baking.' },
      { speaker: 'A', dutch: 'Echt?! Dat wist ik niet. Top, dan is het geregeld!', english: 'Really?! I didn\'t know that. Great, then it\'s sorted!' },
    ],
    expressions: [
      { dutch: 'Helemaal mee eens', english: 'Totally agree / completely in agreement', note: '"Het helemaal ergens mee eens zijn" = to completely agree with something.' },
      { dutch: 'Dat moet lukken', english: 'That should work / that should be doable', note: '"Lukken" = to succeed/work out. "Dat moet lukken" = optimistic "that should be fine".' },
      { dutch: 'Ik ben aan het twijfelen', english: 'I\'m torn / I\'m undecided', note: '"Twijfelen" = to doubt/hesitate. "Aan het twijfelen zijn" = to be in the process of doubting.' },
      { dutch: 'Iemand met dieetwensen', english: 'Anyone with dietary requirements', note: '"Dieetwensen" = dietary wishes/requirements. Essential for hosting in the Netherlands.' },
      { dutch: 'Rekening houden met', english: 'To take into account / to consider', note: '"Er rekening mee houden" = to take something into account. Formal-ish but very common.' },
      { dutch: 'Ik kan best lekker bakken', english: 'I\'m actually quite good at baking', note: '"Best" here = quite/pretty. "Lekker" used as an intensifier for skills too.' },
      { dutch: 'Dan is het geregeld', english: 'Then it\'s sorted / all sorted', note: '"Geregeld" = sorted/arranged. "Dan is het geregeld!" = great, all done!' },
    ],
  },
  {
    id: 'vakantie-plannen',
    title: 'Holiday Plans',
    dutchTitle: 'Vakantie plannen',
    emoji: '✈️',
    description: 'Colleagues comparing summer holiday plans',
    level: 'A2',
    context: 'Two colleagues, Inge and Wouter, are chatting after a meeting about their upcoming holidays.',
    speakers: { A: 'Inge', B: 'Wouter' },
    lines: [
      { speaker: 'A', dutch: 'Wouter, ga jij dit jaar nog ergens op vakantie?', english: 'Wouter, are you going on holiday anywhere this year?' },
      { speaker: 'B', dutch: 'Ja! We gaan in augustus naar Portugal. En jij?', english: 'Yes! We\'re going to Portugal in August. And you?' },
      { speaker: 'A', dutch: 'Wauw leuk! Wij gaan naar Italië, Toscane.', english: 'Wow nice! We\'re going to Italy, Tuscany.' },
      { speaker: 'B', dutch: 'Oh dat is zo mooi daar. Ben je er al eens geweest?', english: 'Oh it\'s so beautiful there. Have you been there before?' },
      { speaker: 'A', dutch: 'Nee, voor het eerst. Ik kijk er enorm naar uit.', english: 'No, first time. I\'m really looking forward to it.' },
      { speaker: 'B', dutch: 'Jullie gaan het geweldig vinden. Het eten alleen al.', english: 'You\'re going to love it. The food alone.' },
      { speaker: 'A', dutch: 'Haha, dat hoop ik! Hoe lang gaan jullie?', english: 'Haha, I hope so! How long are you going?' },
      { speaker: 'B', dutch: 'Twee weken. We hebben een huisje gehuurd aan zee.', english: 'Two weeks. We\'ve rented a little house by the sea.' },
      { speaker: 'A', dutch: 'Klinkt heerlijk. Lekker niksen.', english: 'Sounds wonderful. Nice and doing nothing.' },
      { speaker: 'B', dutch: 'Precies. Geen wekker, geen vergaderingen.', english: 'Exactly. No alarm, no meetings.' },
      { speaker: 'A', dutch: 'Dat gun ik je. We tellen af!', english: 'You deserve it. We\'re counting down!' },
      { speaker: 'B', dutch: 'Jij ook! Geniet ervan straks.', english: 'You too! Enjoy it when the time comes.' },
    ],
    expressions: [
      { dutch: 'Ik kijk er enorm naar uit', english: 'I\'m really looking forward to it', note: '"Ergens naar uitkijken" = to look forward to something. "Enorm" intensifies it.' },
      { dutch: 'Het eten alleen al', english: 'The food alone', note: '"Alleen al" = alone/just. Implies the food is so good it\'s worth the trip by itself.' },
      { dutch: 'Niksen', english: 'Doing absolutely nothing (deliberately)', note: 'A uniquely Dutch concept — the art of doing nothing without guilt. Became internationally known.' },
      { dutch: 'Geen wekker', english: 'No alarm (clock)', note: 'Symbol of holiday freedom in Dutch culture.' },
      { dutch: 'Dat gun ik je', english: 'You deserve it / I\'m glad for you', note: '"Gunnen" = to wish someone well/to not begrudge them something. "Dat gun ik je" is warm and generous.' },
      { dutch: 'We tellen af', english: 'We\'re counting down', note: '"Aftellen" = to count down. Used for anticipated events.' },
      { dutch: 'Geniet ervan straks', english: 'Enjoy it when the time comes', note: '"Straks" = in a while/later. "Geniet ervan" = enjoy it.' },
    ],
  },
]

export function getRealConversation(id: string): RealConversation | undefined {
  return realConversations.find((c) => c.id === id)
}

export function getRandomRealConversation(): RealConversation {
  return realConversations[Math.floor(Math.random() * realConversations.length)]
}
