export interface DialogueLine {
  speaker: 'A' | 'B'
  dutch: string
  english: string
}

export interface Expression {
  dutch: string
  english: string
  note: string
}

export interface RealConversation {
  id: string
  title: string
  dutchTitle: string
  emoji: string
  description: string
  level: 'A1' | 'A2' | 'B1'
  context: string
  speakers: { A: string; B: string }
  lines: DialogueLine[]
  expressions: Expression[]
}

export const realConversations: RealConversation[] = [
  {
    id: 'koffie-werk',
    title: 'Coffee at Work',
    dutchTitle: 'Koffie op het werk',
    emoji: '☕',
    description: 'Two colleagues, bad coffee, worse news',
    level: 'A2',
    context: 'Maandagochtend. Lars staat naar de koffieautomaat te staren. Noor komt erbij.',
    speakers: { A: 'Lars', B: 'Noor' },
    lines: [
      { speaker: 'A', dutch: 'Hé Noor. Koffie?', english: 'Hey Noor. Coffee?' },
      { speaker: 'B', dutch: 'Alsof ik zonder koffie aan een maandag begin. Doe maar.', english: 'As if I\'d start a Monday without coffee. Go ahead / yes please.' },
      { speaker: 'A', dutch: 'Die machine doet het weer niet. Ik heb al drie keer gedrukt.', english: 'That machine isn\'t working again. I\'ve pressed it three times already.' },
      { speaker: 'B', dutch: 'Geef eens. Je moet er echt hard op drukken, zo.', english: 'Let me try. You really have to press hard, like this.' },
      { speaker: 'A', dutch: 'Oh. Dat wist ik niet. Hoe lang werk jij hier al?', english: 'Oh. I didn\'t know that. How long have you worked here?' },
      { speaker: 'B', dutch: 'Vijf jaar. De machine is er al zes. We kennen elkaar goed.', english: 'Five years. The machine\'s been here for six. We know each other well.' },
      { speaker: 'A', dutch: 'Zeg, heb jij die mail van Joost al gelezen?', english: 'Hey, did you read that email from Joost?' },
      { speaker: 'B', dutch: 'Nee. Is het erg?', english: 'No. Is it bad?' },
      { speaker: 'A', dutch: 'Vergadering. Vrijdagmiddag. Verplicht.', english: 'Meeting. Friday afternoon. Mandatory.' },
      { speaker: 'B', dutch: 'Vrijdagmiddag?! Joost is echt niet normaal.', english: 'Friday afternoon?! Joost is genuinely unbelievable.' },
      { speaker: 'A', dutch: 'Nou.', english: 'Right. / Tell me about it.' },
      { speaker: 'B', dutch: 'Eerst maar koffie. Dan pas boos worden.', english: 'Coffee first. Get angry after.' },
      { speaker: 'A', dutch: 'Goed plan.', english: 'Good plan.' },
    ],
    expressions: [
      { dutch: 'Doe maar', english: 'Go ahead / yes please / sure', note: 'The most Dutch phrase. Casual agreement to an offer. You\'ll hear this ten times a day in any Dutch office.' },
      { dutch: 'Geef eens', english: 'Let me try / hand it over', note: '"Eens" softens a request. "Geef eens" = just give it here. Not rude — just direct and casual.' },
      { dutch: 'Hoe lang ... al?', english: 'How long have you been ...?', note: '"Al" signals duration. "Hoe lang werk jij hier al?" = how long have you been working here (already)?' },
      { dutch: 'Zeg', english: 'Hey / listen / by the way', note: 'Used to introduce new info or get attention. Like a verbal tap on the shoulder.' },
      { dutch: 'Echt niet normaal', english: 'Genuinely unbelievable / out of order', note: 'Can mean amazing OR terrible — tone decides. A Friday afternoon mandatory meeting = definitely terrible.' },
      { dutch: 'Nou', english: 'Right / yeah / tell me about it', note: 'One word, infinite meanings. Agreement, resignation, surprise, sarcasm — the Swiss Army knife of Dutch.' },
      { dutch: 'Dan pas', english: 'Only then / after that', note: '"Eerst koffie, dan pas boos worden" = coffee first, THEN get angry. Sets a clear, very Dutch priority order.' },
      { dutch: 'Verplicht', english: 'Mandatory / compulsory', note: 'A word Dutch people dread. "Verplichte vergadering op vrijdagmiddag" is basically a war crime in Dutch office culture.' },
    ],
  },
  {
    id: 'tikkie',
    title: 'Sending a Tikkie',
    dutchTitle: 'Een Tikkie sturen',
    emoji: '📱',
    description: 'The most Dutch thing you\'ll ever do — splitting the bill',
    level: 'A1',
    context: 'Na een etentje. De rekening is betaald door Emma. Nu wil ze haar geld terug.',
    speakers: { A: 'Emma', B: 'Daan' },
    lines: [
      { speaker: 'A', dutch: 'Daan, ik stuur je even een Tikkie voor gisteravond.', english: 'Daan, I\'ll just send you a Tikkie for last night.' },
      { speaker: 'B', dutch: 'Ja doe maar. Hoeveel was het ook alweer?', english: 'Yeah go ahead. How much was it again?' },
      { speaker: 'A', dutch: 'Jij had de pasta en een biertje. Dat was veertien vijftig.', english: 'You had the pasta and a beer. That was fourteen fifty.' },
      { speaker: 'B', dutch: 'Oke, ik zie hem. Even pinnen... gedaan.', english: 'Okay, I see it. Let me pay... done.' },
      { speaker: 'A', dutch: 'Top, ontvangen. En Sanne? Heeft ze al betaald?', english: 'Great, received. And Sanne? Has she paid yet?' },
      { speaker: 'B', dutch: 'Geen idee. Stuur haar ook een Tikkie, anders vergeet ze het.', english: 'No idea. Send her one too, otherwise she\'ll forget.' },
      { speaker: 'A', dutch: 'Ik heb haar al twee keer herinnerd hoor.', english: 'I\'ve already reminded her twice, you know.' },
      { speaker: 'B', dutch: 'Tja. Je kent Sanne.', english: 'Well. You know Sanne.' },
      { speaker: 'A', dutch: 'Ik stuur gewoon een berichtje. "Sanne, Tikkie 😊"', english: 'I\'ll just send a message. "Sanne, Tikkie 😊"' },
      { speaker: 'B', dutch: 'Met een smiley erbij. Dan kan ze niet nee zeggen.', english: 'With a smiley. Then she can\'t say no.' },
      { speaker: 'A', dutch: 'Precies. De emoji doet het werk.', english: 'Exactly. The emoji does the work.' },
    ],
    expressions: [
      { dutch: 'Een Tikkie sturen', english: 'To send a payment request (via Tikkie app)', note: 'Tikkie is a Dutch payment request app. "Ik stuur je een Tikkie" = I\'ll send you a bill. Now a verb in Dutch culture.' },
      { dutch: 'Hoe veel was het ook alweer?', english: 'How much was it again?', note: '"Ook alweer" = "again" when you\'ve forgotten something. Very natural in casual conversation.' },
      { dutch: 'Even pinnen', english: 'Just paying by card / let me pay', note: '"Pinnen" = to pay by debit card. The Dutch verb for card payment. "Even" makes it sound quick and easy.' },
      { dutch: 'Ontvangen', english: 'Received', note: 'Short confirmation that money or a message arrived. Used in chat all the time: "ontvangen, thanks!"' },
      { dutch: 'Anders vergeet ze het', english: 'Otherwise she\'ll forget', note: '"Anders" = otherwise. "Anders doe ik het niet" = otherwise I won\'t do it. Very useful linking word.' },
      { dutch: 'Tja', english: 'Well / yeah, what can you do', note: 'A sigh in word form. "Tja" means you accept something even if you don\'t love it. Between "yep" and a shrug.' },
      { dutch: 'Je kent [naam]', english: 'You know what [name] is like', note: 'Explaining someone\'s behaviour by referencing their personality. "Je kent Sanne" = you know how she is.' },
      { dutch: 'De emoji doet het werk', english: 'The emoji does the work', note: 'A very modern Dutch expression. A 😊 after a money request softens everything. Widely understood.' },
    ],
  },
  {
    id: 'trein-vertraging',
    title: 'Train Delay',
    dutchTitle: 'De trein heeft vertraging',
    emoji: '🚆',
    description: 'Strangers bonding on a platform — a Dutch national sport',
    level: 'A2',
    context: 'Perron 7, Utrecht Centraal. Het bord zegt "vertraging onbekend". Fatima en Bas staan al twintig minuten te wachten.',
    speakers: { A: 'Fatima', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Weet jij ook niet wat er aan de hand is?', english: 'Do you also not know what\'s going on?' },
      { speaker: 'B', dutch: 'Nee. Het bord zegt al een kwartier "vertraging onbekend".', english: 'No. The board has been saying "delay unknown" for fifteen minutes.' },
      { speaker: 'A', dutch: 'Onbekend. Geweldig.', english: 'Unknown. Wonderful. (sarcastic)' },
      { speaker: 'B', dutch: 'Heb je de NS-app? Die is ook al niks waard vandaag.', english: 'Do you have the NS app? That\'s useless today too.' },
      { speaker: 'A', dutch: 'Een seinstoring ergens, denk ik. Toch te gek.', english: 'A signal failure somewhere, I think. Absolutely ridiculous.' },
      { speaker: 'B', dutch: 'Ik betaal tweehonderd euro per maand voor dit abonnement.', english: 'I pay two hundred euros a month for this subscription.' },
      { speaker: 'A', dutch: 'Ik ook. En toch staan we hier.', english: 'Me too. And yet here we stand.' },
      { speaker: 'B', dutch: 'Heb jij een vergadering?', english: 'Do you have a meeting?' },
      { speaker: 'A', dutch: 'Om negen uur. Stuur maar een appje naar je baas: "NS".', english: 'At nine. Just send your boss a WhatsApp: "NS".' },
      { speaker: 'B', dutch: 'Haha. Tegenwoordig is dat gewoon een officiële reden.', english: 'Haha. Nowadays that\'s just an official reason.' },
      { speaker: 'A', dutch: 'Echt zo. Oh, hij komt eraan!', english: 'So true. Oh, it\'s coming!' },
      { speaker: 'B', dutch: 'Eindelijk. Niet instappen voor de gele streep!', english: 'Finally. Don\'t board before the yellow line!' },
      { speaker: 'A', dutch: 'Dat zeg je alsof ik nieuw ben hier.', english: 'You say that as if I\'m new here.' },
    ],
    expressions: [
      { dutch: 'Wat is er aan de hand?', english: 'What\'s going on? / What\'s wrong?', note: 'Go-to phrase when something\'s off. Works for train delays, weird silences, arguments — everything.' },
      { dutch: 'Niks waard', english: 'Useless / worthless', note: '"Niks waard zijn" = to be worth nothing. "De app is niks waard vandaag" = the app is completely useless today.' },
      { dutch: 'Toch te gek', english: 'Absolutely ridiculous / unreal', note: '"Te gek" = too crazy. With "toch" it adds extra disbelief. Can be positive or negative depending on context.' },
      { dutch: 'En toch', english: 'And yet / still', note: 'Shows irony or contradiction. "I pay €200 and yet I\'m stuck here." Very expressive little phrase.' },
      { dutch: 'Stuur maar een appje', english: 'Just send a WhatsApp', note: '"Appen" is now a Dutch verb. "Ik app je" = I\'ll WhatsApp you. Central to Dutch communication.' },
      { dutch: 'Tegenwoordig', english: 'Nowadays / these days', note: 'Easy word to make sentences sound more fluent. "Tegenwoordig doet iedereen dat" = everyone does that nowadays.' },
      { dutch: 'Echt zo', english: 'So true / exactly right', note: 'Short, punchy agreement. "Echt zo!" = couldn\'t agree more. Very natural in casual conversation.' },
      { dutch: 'Niet voor de gele streep', english: 'Not before the yellow line', note: 'A very Dutch platform instruction. The yellow line marks where you wait. Stepping over it = disapproving looks.' },
    ],
  },
  {
    id: 'albert-heijn',
    title: 'At the Albert Heijn',
    dutchTitle: 'Bij de Albert Heijn',
    emoji: '🧡',
    description: 'Self-checkout chaos, a very Dutch Saturday morning',
    level: 'A1',
    context: 'Zaterdagochtend bij de AH. Druk. Yara staat bij de zelfscankassa. Die doet het niet.',
    speakers: { A: 'Yara', B: 'Medewerker Tim' },
    lines: [
      { speaker: 'A', dutch: 'Excuseer, deze kassa doet het niet. Hij zegt steeds "onbekend artikel".', english: 'Excuse me, this checkout isn\'t working. It keeps saying "unknown item".' },
      { speaker: 'B', dutch: 'Wat heeft u gescand?', english: 'What did you scan?' },
      { speaker: 'A', dutch: 'De komkommer. Met de sticker en alles.', english: 'The cucumber. With the sticker and everything.' },
      { speaker: 'B', dutch: 'Heeft u ook de bonuskaart gescand?', english: 'Did you also scan the bonus card?' },
      { speaker: 'A', dutch: 'Ehm... nee. Hoe doe ik dat?', english: 'Umm... no. How do I do that?' },
      { speaker: 'B', dutch: 'Met de app op uw telefoon. Mag ik even?', english: 'With the app on your phone. May I just?' },
      { speaker: 'A', dutch: 'Ja hoor. Oh, en kan ik vragen — waar is de hagelslag?', english: 'Of course. Oh, and can I ask — where is the hagelslag?' },
      { speaker: 'B', dutch: 'Gangpad drie, bij het broodbeleg. Links.', english: 'Aisle three, with the bread toppings. On the left.' },
      { speaker: 'A', dutch: 'Top. En de komkommer?', english: 'Great. And the cucumber?' },
      { speaker: 'B', dutch: 'Opgelost. U kunt doorgaan.', english: 'Sorted. You can continue.' },
      { speaker: 'A', dutch: 'Kan ik hier ook met iDEAL betalen?', english: 'Can I also pay with iDEAL here?' },
      { speaker: 'B', dutch: 'Alleen pin of contant bij de zelfscankassa, helaas.', english: 'Only card or cash at the self-checkout, unfortunately.' },
      { speaker: 'A', dutch: 'Dan maar pinnen. Bedankt voor de hulp!', english: 'Then I\'ll just pay by card. Thanks for the help!' },
    ],
    expressions: [
      { dutch: 'Met de sticker en alles', english: 'With the sticker and everything', note: '"En alles" = and everything / the whole thing. Adds mild frustration — I did everything right!' },
      { dutch: 'Mag ik even?', english: 'May I just? / Can I quickly?', note: 'THE Dutch way to ask for something briefly. "Even" makes it sound quick and harmless. Used constantly.' },
      { dutch: 'Ja hoor', english: 'Of course / yes go ahead / sure', note: '"Hoor" adds a warm, reassuring tone. "Ja hoor" = yes, absolutely, no problem at all.' },
      { dutch: 'Opgelost', english: 'Sorted / fixed / solved', note: '"Oplossen" = to solve. "Opgelost!" as a standalone = all fixed! Very satisfying word.' },
      { dutch: 'U kunt doorgaan', english: 'You can continue / carry on', note: 'Formal "u" is used in shops and services. "Doorgaan" = to continue or proceed.' },
      { dutch: 'Helaas', english: 'Unfortunately / sadly', note: 'Gentle Dutch word for "unfortunately". Less harsh than "sorry, nee". Softens bad news.' },
      { dutch: 'Dan maar pinnen', english: 'Then I\'ll just pay by card', note: '"Dan maar" = in that case, I\'ll just... Accepting a limitation a bit reluctantly but without fuss.' },
      { dutch: 'Hagelslag', english: 'Chocolate sprinkles (for on bread)', note: 'Dutch people put chocolate sprinkles on buttered bread for breakfast. This is completely normal and deeply cultural.' },
    ],
  },
  {
    id: 'ze-spreken-engels',
    title: 'They Switch to English',
    dutchTitle: 'Ze spreken meteen Engels',
    emoji: '🇬🇧',
    description: 'Every Dutch learner\'s most frustrating daily experience',
    level: 'A2',
    context: 'Een koffiebar. Lena (aan het leren Nederlands) probeert te bestellen. De barista switcht direct naar Engels.',
    speakers: { A: 'Lena', B: 'Barista Noah' },
    lines: [
      { speaker: 'A', dutch: 'Hallo! Mag ik een koffie verkeerd, alsjeblieft?', english: 'Hello! Can I have a koffie verkeerd, please?' },
      { speaker: 'B', dutch: 'Sure! For here or to go?', english: '(switching to English) Sure! For here or to go?' },
      { speaker: 'A', dutch: 'Eh... voor hier. Sorry, mag ik in het Nederlands bestellen?', english: 'Uh... for here. Sorry, can I order in Dutch?' },
      { speaker: 'B', dutch: 'Oh! Ja tuurlijk, sorry. Ik doe het automatisch.', english: 'Oh! Yes of course, sorry. I do it automatically.' },
      { speaker: 'A', dutch: 'Geeft niet. Ik oefen Nederlands. Het helpt als mensen Dutch met me praten.', english: 'No worries. I\'m practising Dutch. It helps when people speak Dutch with me.' },
      { speaker: 'B', dutch: 'Dat snap ik. Jouw Nederlands klinkt al goed, eerlijk gezegd.', english: 'I understand that. Your Dutch already sounds good, honestly.' },
      { speaker: 'A', dutch: 'Dankjewel! Ik maak nog veel fouten.', english: 'Thank you! I still make a lot of mistakes.' },
      { speaker: 'B', dutch: 'Maakt niet uit. Gewoon blijven oefenen. Wil je er iets bij?', english: 'Doesn\'t matter. Just keep practising. Do you want anything with it?' },
      { speaker: 'A', dutch: 'Een stuk appeltaart, als dat kan.', english: 'A slice of apple pie, if that\'s possible.' },
      { speaker: 'B', dutch: 'Uiteraard. Komt eraan!', english: 'Of course. Coming right up!' },
      { speaker: 'A', dutch: 'Super. En... bedankt dat je Nederlands met me praat.', english: 'Great. And... thanks for speaking Dutch with me.' },
      { speaker: 'B', dutch: 'Geen probleem. Zo leer je het het snelst.', english: 'No problem. That\'s how you learn it fastest.' },
    ],
    expressions: [
      { dutch: 'Ik doe het automatisch', english: 'I do it automatically / out of habit', note: 'Dutch people switch to English automatically when they hear an accent. It\'s kind — but not helpful for learners.' },
      { dutch: 'Geeft niet', english: 'No worries / that\'s okay / doesn\'t matter', note: 'One of the warmest Dutch phrases. "Geeft niet" = it doesn\'t give (anything bad). Universal reassurance.' },
      { dutch: 'Eerlijk gezegd', english: 'Honestly / to be honest', note: 'Adds sincerity. "Eerlijk gezegd vind ik het moeilijk" = honestly, I find it difficult.' },
      { dutch: 'Maakt niet uit', english: 'Doesn\'t matter / never mind', note: 'Close cousin of "geeft niet". "Maakt niet uit" = it doesn\'t make a difference. Very calming phrase.' },
      { dutch: 'Gewoon blijven oefenen', english: 'Just keep practising', note: '"Gewoon" = just/simply. "Blijven + infinitive" = to keep doing something. "Blijven oefenen" = keep practising.' },
      { dutch: 'Als dat kan', english: 'If that\'s possible / if you can', note: 'Polite add-on to a request. Makes it sound less demanding. "Een stuk taart, als dat kan" = very polite.' },
      { dutch: 'Uiteraard', english: 'Of course / naturally', note: 'Slightly more formal than "tuurlijk". Sounds confident and professional. Great for service situations.' },
      { dutch: 'Zo leer je het het snelst', english: 'That\'s how you learn it fastest', note: 'A reassuring sentence structure. "Zo + verb + je + het" = that\'s how you do it.' },
    ],
  },
  {
    id: 'snackbar',
    title: 'At the Snackbar',
    dutchTitle: 'Bij de snackbar',
    emoji: '🍟',
    description: 'The most Dutch fast food experience on earth',
    level: 'A1',
    context: 'Vrijdagavond. Rick staat bij de snackbar. Hij weet nog niet precies wat hij wil.',
    speakers: { A: 'Rick', B: 'Mevrouw achter de toonbank' },
    lines: [
      { speaker: 'A', dutch: 'Goedenavond! Mag ik een frikandel speciaal?', english: 'Good evening! Can I have a frikandel speciaal?' },
      { speaker: 'B', dutch: 'Komt eraan. Wil je er friet bij?', english: 'Coming up. Do you want fries with it?' },
      { speaker: 'A', dutch: 'Ja graag. Grote of kleine?', english: 'Yes please. Large or small?' },
      { speaker: 'B', dutch: 'Groot is anderhalve euro meer.', english: 'Large is one fifty more.' },
      { speaker: 'A', dutch: 'Dan maar groot. Doe maar met mayo.', english: 'Then I\'ll take large. With mayo please.' },
      { speaker: 'B', dutch: 'Alleen mayo of ook ketchup en ui?', english: 'Just mayo or ketchup and onion too?' },
      { speaker: 'A', dutch: 'Alleen mayo. En... bestaat er ook een kroket?', english: 'Just mayo. And... do you also have a kroket?' },
      { speaker: 'B', dutch: 'Altijd! Runder of kaas?', english: 'Always! Beef or cheese?' },
      { speaker: 'A', dutch: 'Runder graag. Eén dan.', english: 'Beef please. One then.' },
      { speaker: 'B', dutch: 'Dat wordt zeven tachtig bij elkaar.', english: 'That comes to seven eighty altogether.' },
      { speaker: 'A', dutch: 'Kan ik pinnen?', english: 'Can I pay by card?' },
      { speaker: 'B', dutch: 'Helaas, alleen contant hier.', english: 'Unfortunately, cash only here.' },
      { speaker: 'A', dutch: 'Even kijken... ja, ik heb het precies.', english: 'Let me check... yes, I have it exactly.' },
      { speaker: 'B', dutch: 'Top! Smakelijk!', english: 'Great! Enjoy your meal!' },
    ],
    expressions: [
      { dutch: 'Komt eraan', english: 'Coming right up / on its way', note: 'Standard response in any Dutch food place. "Komt eraan!" = it\'s coming. Warm and efficient.' },
      { dutch: 'Doe maar met mayo', english: 'With mayo please / mayo it is', note: '"Doe maar" is the ultimate casual Dutch phrase. "Doe maar met mayo" = just go with mayo.' },
      { dutch: 'Bestaat er ook...?', english: 'Do you also have...? / Is there also...?', note: '"Bestaat er" literally = does there exist. A natural way to ask if something is available.' },
      { dutch: 'Bij elkaar', english: 'Altogether / in total', note: '"Dat wordt X euro bij elkaar" = that comes to X euros total. Essential for shopping and ordering.' },
      { dutch: 'Even kijken', english: 'Let me check / just looking', note: '"Even" makes everything casual. "Even kijken" = give me a sec. Said while checking pockets, a menu, a screen.' },
      { dutch: 'Ik heb het precies', english: 'I have it exactly / exact change', note: '"Het precies hebben" = to have exact change. Much appreciated at small Dutch cash-only businesses.' },
      { dutch: 'Smakelijk!', english: 'Enjoy your meal! / Bon appétit!', note: 'Short for "eet smakelijk". Said before and during meals. Respond with "dankjewel, u ook!"' },
      { dutch: 'Frikandel speciaal', english: 'Frikandel with mayo, ketchup and raw onion', note: 'THE Dutch snack. A fried meat stick with three sauces. If you haven\'t tried it, you haven\'t lived in NL.' },
    ],
  },
  {
    id: 'borrel',
    title: 'The Borrel',
    dutchTitle: 'Borrel na het werk',
    emoji: '🍺',
    description: 'Friday afternoon drinks — the Dutch social ritual',
    level: 'A2',
    context: 'Vrijdagmiddag, net na vijven. Iedereen gaat naar de kroeg naast het kantoor.',
    speakers: { A: 'Fleur', B: 'Diederik' },
    lines: [
      { speaker: 'A', dutch: 'Diederik, ga je mee naar de borrel?', english: 'Diederik, are you coming to the drinks?' },
      { speaker: 'B', dutch: 'Tuurlijk! Eén biertje dan. Ik moet om zeven uur thuis zijn.', english: 'Of course! Just one beer. I need to be home by seven.' },
      { speaker: 'A', dutch: 'Dat zeg je elke week.', english: 'You say that every week.' },
      { speaker: 'B', dutch: 'En elke week meen ik het. Tot het tweede biertje.', english: 'And every week I mean it. Until the second beer.' },
      { speaker: 'A', dutch: 'Haha. Wat wil je drinken? Ik ga even naar de bar.', english: 'Haha. What do you want to drink? I\'ll just go to the bar.' },
      { speaker: 'B', dutch: 'Een pilsje. Oh en kijk of ze ook bitterballen hebben.', english: 'A lager. Oh and check if they have bitterballen too.' },
      { speaker: 'A', dutch: 'Dat hebben ze altijd hier. Dat weet je.', english: 'They always have those here. You know that.' },
      { speaker: 'B', dutch: 'Ik vraag het toch maar even.', english: 'I\'m just asking anyway.' },
      { speaker: 'A', dutch: 'Goed. En let op, die zijn altijd gloeiend heet van binnen.', english: 'Okay. And watch out, they\'re always scorching hot inside.' },
      { speaker: 'B', dutch: 'Dat weet ik ook na tien jaar. Maar ik doe het toch.', english: 'I know that after ten years too. But I still do it anyway.' },
      { speaker: 'A', dutch: 'Haha. Nederlanders en bitterballen. Onverwoestbaar.', english: 'Haha. Dutch people and bitterballen. Unbreakable.' },
      { speaker: 'B', dutch: 'Op het weekend!', english: 'To the weekend!' },
      { speaker: 'A', dutch: 'Op het weekend!', english: 'To the weekend!' },
    ],
    expressions: [
      { dutch: 'Tuurlijk', english: 'Of course / obviously', note: 'Casual version of "natuurlijk". Very common in spoken Dutch. Shows enthusiasm or obvious agreement.' },
      { dutch: 'Dat zeg je elke week', english: 'You say that every week', note: 'Calling out a pattern in someone\'s behaviour. Gently teasing. Very natural in friendships.' },
      { dutch: 'Tot het tweede biertje', english: 'Until the second beer', note: '"Tot" = until. "Tot X" sets a limit. "Tot het tweede biertje" = fine, until drink number two arrives.' },
      { dutch: 'Een pilsje', english: 'A (small) lager / a beer', note: '"Pilsje" = a glass of pilsner beer. The diminutive "-je" makes it sound casual and light. Standard at a Dutch borrel.' },
      { dutch: 'Dat weet je', english: 'You know that', note: 'Slightly teasing confirmation. "Dat weet je" = you already know this. Can be warm or gently exasperated.' },
      { dutch: 'Toch maar even', english: 'Asking anyway / just checking anyway', note: '"Toch maar even" = doing something anyway even though it might not be necessary. Very Dutch hedge.' },
      { dutch: 'Gloeiend heet', english: 'Scorching hot / boiling hot', note: '"Gloeiend" intensifies heat dramatically. Bitterballen are always dangerous inside. Always. No exceptions.' },
      { dutch: 'Op het weekend!', english: 'To the weekend! (toast)', note: 'Friday borrel toast. Lift your glass, say this, everyone agrees. The most popular borrel toast in the Netherlands.' },
    ],
  },
  {
    id: 'verjaardag-party',
    title: 'Birthday Plans',
    dutchTitle: 'Verjaardag plannen',
    emoji: '🎂',
    description: 'Organising a surprise party — Dutch edition',
    level: 'A2',
    context: 'Roos belt Joep. Lotte wordt zaterdag dertig en niemand heeft iets geregeld.',
    speakers: { A: 'Roos', B: 'Joep' },
    lines: [
      { speaker: 'A', dutch: 'Joep. Lotte. Zaterdag. Dertig. Wat doen we?', english: 'Joep. Lotte. Saturday. Thirty. What are we doing?' },
      { speaker: 'B', dutch: 'O nee. Ik had dat helemaal vergeten.', english: 'Oh no. I had completely forgotten that.' },
      { speaker: 'A', dutch: 'Dat weet ik. Daarom bel ik jou.', english: 'I know. That\'s why I\'m calling you.' },
      { speaker: 'B', dutch: 'Oké oké. Verrassingsfeestje bij jou thuis?', english: 'Okay okay. Surprise party at yours?' },
      { speaker: 'A', dutch: 'Ze weet van niks. Twintig man, niet te groot.', english: 'She has no idea. Twenty people, not too big.' },
      { speaker: 'B', dutch: 'Ik regel de drank als jij het eten doet.', english: 'I\'ll sort the drinks if you do the food.' },
      { speaker: 'A', dutch: 'Deal. En iemand moet haar erheen lokken zonder dat ze argwaan krijgt.', english: 'Deal. And someone needs to lure her there without her getting suspicious.' },
      { speaker: 'B', dutch: 'Sanne. Die liegt het beste van ons allemaal.', english: 'Sanne. She\'s the best liar out of all of us.' },
      { speaker: 'A', dutch: 'Ideaal. Ik maak een appgroep aan — let op dat Lotte er niet in zit.', english: 'Perfect. I\'ll make a WhatsApp group — make sure Lotte\'s not in it.' },
      { speaker: 'B', dutch: 'Ja hallo, dat snap ik zelf ook wel.', english: 'Oh come on, I know that myself.' },
      { speaker: 'A', dutch: 'Sorry sorry. Oh, en geen taart van de AH dit keer.', english: 'Sorry sorry. Oh, and no cake from the AH this time.' },
      { speaker: 'B', dutch: 'Die was vorig jaar inderdaad droog.', english: 'That one was indeed dry last year.' },
      { speaker: 'A', dutch: 'Van de bakkerij op de hoek. Afgesproken?', english: 'From the bakery on the corner. Agreed?' },
      { speaker: 'B', dutch: 'Afgesproken. Ik regel het.', english: 'Agreed. I\'ll sort it.' },
    ],
    expressions: [
      { dutch: 'Ze weet van niks', english: 'She has no idea / she doesn\'t know anything', note: 'Perfect for surprise planning. "Van niks weten" = to be completely in the dark about something.' },
      { dutch: 'Ik regel het', english: 'I\'ll sort it / I\'ll handle it', note: '"Regelen" = to arrange/sort. Dutch people "regelen" everything. When a Dutch person says this, it gets done.' },
      { dutch: 'Argwaan krijgen', english: 'To get suspicious / to become suspicious', note: '"Argwaan" = suspicion. "Argwaan krijgen" = to start getting suspicious. Great word for dramatic situations.' },
      { dutch: 'Ideaal', english: 'Perfect / ideal / great fit', note: '"Ideaal!" when something fits perfectly. More enthusiastic than it looks — said with a satisfied nod.' },
      { dutch: 'Ja hallo', english: 'Oh come on / give me some credit / obviously', note: 'Mild pushback when someone states the obvious. "Ja hallo, dat weet ik zelf ook." Not rude — just Dutch.' },
      { dutch: 'Afgesproken', english: 'Agreed / deal / it\'s settled', note: 'The Dutch handshake in word form. "Afgesproken" closes a deal. Satisfying, final, done.' },
      { dutch: 'Op de hoek', english: 'On the corner', note: '"De hoek" = the corner. "Op de hoek" = on the corner. Very useful for giving directions in Dutch cities.' },
      { dutch: 'Van ons allemaal', english: 'Out of all of us / among all of us', note: '"Van ons allemaal" = among/of all of us. "De beste van ons allemaal" = the best one of our group.' },
    ],
  },
  {
    id: 'weer-klagen',
    title: 'About the Weather',
    dutchTitle: 'Weer klagen over het weer',
    emoji: '🌧️',
    description: 'The Dutch national pastime — now with extra wind',
    level: 'A1',
    context: 'Buiten. Het regent. Henk en Marjolein staan bij de brievenbus. Het heeft de hele week al geregend.',
    speakers: { A: 'Henk', B: 'Marjolein' },
    lines: [
      { speaker: 'A', dutch: 'Goedemorgen Marjolein. Wat een weer, hè?', english: 'Good morning Marjolein. What weather, huh?' },
      { speaker: 'B', dutch: 'Vreselijk. Ik ben al drie keer op de fiets gevallen dit jaar.', english: 'Terrible. I\'ve already fallen off my bike three times this year.' },
      { speaker: 'A', dutch: 'Door de regen?', english: 'Because of the rain?' },
      { speaker: 'B', dutch: 'Regen én wind. Gisteren woei mijn paraplu binnenstebuiten.', english: 'Rain AND wind. Yesterday my umbrella blew inside out.' },
      { speaker: 'A', dutch: 'Haha! Paraplu\'s zijn nutteloos hier. Je hebt er niks aan.', english: 'Haha! Umbrellas are useless here. They\'re no good.' },
      { speaker: 'B', dutch: 'Toch koop ik er elk jaar een nieuwe. En hij gaat elk jaar kapot.', english: 'And yet I buy a new one every year. And it breaks every year.' },
      { speaker: 'A', dutch: 'Hebben ze ook gezegd dat het zondag beter wordt?', english: 'Did they also say it\'ll be better on Sunday?' },
      { speaker: 'B', dutch: 'Elke week. Ik geloof de buienradar allang niet meer.', english: 'Every week. I stopped trusting the weather app long ago.' },
      { speaker: 'A', dutch: 'Maar goed, wat wil je. Het is Nederland.', english: 'But well, what do you expect. It\'s the Netherlands.' },
      { speaker: 'B', dutch: 'Zo is dat. Jij gaat er toch ook wel aan wennen.', english: 'That\'s right. You\'ll get used to it eventually too.' },
      { speaker: 'A', dutch: 'Ik woon hier al twaalf jaar, Marjolein.', english: 'I\'ve been living here for twelve years, Marjolein.' },
      { speaker: 'B', dutch: 'En toch klaag je nog elke dag.', english: 'And yet you still complain every day.' },
      { speaker: 'A', dutch: 'Dat hoort erbij. Hou je droog!', english: 'That\'s part of it. Stay dry!' },
    ],
    expressions: [
      { dutch: 'Wat een weer, hè?', english: 'What weather, huh?', note: 'Universal Dutch conversation starter. Works with strangers, neighbours, anyone. 100% safe opener.' },
      { dutch: 'Je hebt er niks aan', english: 'It\'s no use / it\'s useless', note: '"Ergens niks aan hebben" = something is no use to you. "Die paraplu is nergens goed voor" means the same.' },
      { dutch: 'Allang niet meer', english: 'Stopped long ago / haven\'t for ages', note: '"Allang" = for a long time already. "Allang niet meer" = stopped doing something ages ago. Very natural.' },
      { dutch: 'Maar goed, wat wil je', english: 'But well, what do you expect', note: 'The Dutch phrase for accepting something annoying but inevitable. Pure resignation, no anger.' },
      { dutch: 'Zo is dat', english: 'That\'s right / that\'s how it is', note: 'Confirming agreement or an unavoidable truth. "Zo is dat" = yep, that\'s just the reality.' },
      { dutch: 'Eraan wennen', english: 'To get used to it', note: '"Wennen aan iets" = to get used to something. "Je went eraan" = you\'ll get used to it. Often said about Dutch weather.' },
      { dutch: 'Dat hoort erbij', english: 'That\'s part of it / goes with the territory', note: '"Erbij horen" = to belong to something, to be part of the package. Complaining about weather hoort erbij.' },
      { dutch: 'Hou je droog', english: 'Stay dry', note: 'The most Dutch farewell in autumn and winter. More realistic than "have a nice day" given the climate.' },
    ],
  },
  {
    id: 'ov-chipkaart',
    title: 'OV-chipkaart',
    dutchTitle: 'OV-chipkaart opladen',
    emoji: '🚌',
    description: 'Dealing with the Dutch transit card system',
    level: 'A2',
    context: 'Een NS-servicepoint. Mia staat bij de balie. Haar OV-chipkaart heeft te weinig saldo.',
    speakers: { A: 'Mia', B: 'NS Medewerker' },
    lines: [
      { speaker: 'A', dutch: 'Goedemiddag. Mijn OV-chipkaart heeft te weinig saldo. Ik ben ingecheckt maar kon niet uitchecken.', english: 'Good afternoon. My OV-chipkaart doesn\'t have enough credit. I checked in but couldn\'t check out.' },
      { speaker: 'B', dutch: 'Dat komt vaker voor. Heeft u de kaart bij u?', english: 'That happens more often. Do you have the card with you?' },
      { speaker: 'A', dutch: 'Ja, hier. Er staat nog maar vijftig cent op.', english: 'Yes, here. There\'s only fifty cents left on it.' },
      { speaker: 'B', dutch: 'U moet minimaal twintig euro opladen om in te mogen checken.', english: 'You need to top up a minimum of twenty euros to be allowed to check in.' },
      { speaker: 'A', dutch: 'Twintig euro? Kan ik ook minder doen?', english: 'Twenty euros? Can I do less?' },
      { speaker: 'B', dutch: 'Het minimum is tien euro. Maar goedkoper per keer is de OV-app.', english: 'The minimum is ten euros. But cheaper per time is the OV app.' },
      { speaker: 'A', dutch: 'Ik heb die app nog niet. Hoe werkt dat?', english: 'I don\'t have that app yet. How does that work?' },
      { speaker: 'B', dutch: 'U koppelt uw bankrekening eraan. Dan betaalt u achteraf per rit.', english: 'You link your bank account to it. Then you pay afterwards per journey.' },
      { speaker: 'A', dutch: 'Oh, dat is makkelijker. Maar nu?', english: 'Oh, that\'s easier. But for now?' },
      { speaker: 'B', dutch: 'Nu laadt u gewoon op. Pinnen kan hier.', english: 'For now you just top up. You can pay by card here.' },
      { speaker: 'A', dutch: 'Oké. Dan maar tien euro. En de boete voor niet uitchecken?', english: 'Okay. Ten euros then. And the fine for not checking out?' },
      { speaker: 'B', dutch: 'Dat lossen we nu ook even op. Dat komt automatisch goed als u dezelfde dag incheckt.', english: 'We\'ll sort that now too. It automatically resolves if you check in on the same day.' },
      { speaker: 'A', dutch: 'Oef, dat scheelde. Bedankt voor de uitleg!', english: 'Phew, that was close. Thanks for the explanation!' },
    ],
    expressions: [
      { dutch: 'Dat komt vaker voor', english: 'That happens more often / that\'s not unusual', note: 'Reassuring phrase. "Dat komt vaker voor" = you\'re not the only one, this is a common thing.' },
      { dutch: 'U moet minimaal ... opladen', english: 'You need to top up at least ...', note: '"Minimaal" = at minimum. "Opladen" = to charge/top up (a card, phone, battery).' },
      { dutch: 'Goedkoper per keer', english: 'Cheaper per time / per instance', note: '"Per keer" = per time/instance. Comparing costs per journey or per use.' },
      { dutch: 'U koppelt ... eraan', english: 'You link ... to it', note: '"Koppelen aan" = to link/connect to. "Uw bankrekening eraan koppelen" = link your bank account to it.' },
      { dutch: 'Achteraf betalen', english: 'Pay afterwards / pay post-use', note: '"Achteraf" = afterwards/after the fact. "Achteraf betalen" is common in Dutch payment systems.' },
      { dutch: 'Dan maar tien euro', english: 'Ten euros then / I\'ll do ten euros', note: '"Dan maar" = okay fine, in that case. Accepting a minimum or compromise without drama.' },
      { dutch: 'Dat lossen we op', english: 'We\'ll sort that / we\'ll fix that', note: '"Oplossen" = to solve/fix. "Dat lossen we even op" = let\'s just sort that quickly. Action-oriented.' },
      { dutch: 'Oef, dat scheelde', english: 'Phew, that was close / that was nearly bad', note: '"Dat scheelde" = that was nearly (a problem). "Oef, dat scheelde!" = phew, lucky escape!' },
    ],
  },
  {
    id: 'nieuwe-baan',
    title: 'New Job',
    dutchTitle: 'Ik heb een nieuwe baan!',
    emoji: '🎉',
    description: 'Good news deserves a beer, immediately',
    level: 'A2',
    context: 'Sophie stuurt Rick een voice memo. Dan belt hij meteen terug.',
    speakers: { A: 'Sophie', B: 'Rick' },
    lines: [
      { speaker: 'A', dutch: 'Rick! Ik heb een nieuwe baan!', english: 'Rick! I got a new job!' },
      { speaker: 'B', dutch: 'Wát?! Vertel! Nu! Alles!', english: 'What?! Tell me! Now! Everything!' },
      { speaker: 'A', dutch: 'Een startup in Amsterdam. UX design. Mijn drooombaan.', english: 'A startup in Amsterdam. UX design. My dream job.' },
      { speaker: 'B', dutch: 'Dat meen je niet. Hoe ben je erbij gekomen?', english: 'You can\'t be serious. How did you get it?' },
      { speaker: 'A', dutch: 'Via LinkedIn. Ze kwamen zelf naar mij toe. Ik had niet eens gesolliciteerd.', english: 'Via LinkedIn. They came to me themselves. I hadn\'t even applied.' },
      { speaker: 'B', dutch: 'Dat is logisch. Jij bent gewoon goed.', english: 'That makes sense. You\'re just good at what you do.' },
      { speaker: 'A', dutch: 'Doe normaal.', english: 'Stop it / come off it.' },
      { speaker: 'B', dutch: 'Echt! Goed verdiend. Wanneer begin je?', english: 'Seriously! Well deserved. When do you start?' },
      { speaker: 'A', dutch: 'Volgende maand. Het voelt nog een beetje onwerkelijk.', english: 'Next month. It still feels a bit unreal.' },
      { speaker: 'B', dutch: 'Dat snap ik. Maar dit moet gevierd worden. Vanavond?', english: 'I get that. But this needs celebrating. Tonight?' },
      { speaker: 'A', dutch: 'Ik had al op je gerekend.', english: 'I was already counting on you.' },
      { speaker: 'B', dutch: 'Ik sta al bij de deur. Op jou!', english: 'I\'m already at the door. To you!' },
    ],
    expressions: [
      { dutch: 'Dat meen je niet', english: 'You can\'t be serious / no way!', note: '"Menen" = to mean/be serious. "Dat meen je niet!" = enthusiastic disbelief. Said with a big smile.' },
      { dutch: 'Ze kwamen naar mij toe', english: 'They came to me', note: '"Naar mij toe" = toward me / to me. Direction is important in Dutch. "Naartoe" = towards.' },
      { dutch: 'Ik had niet eens gesolliciteerd', english: 'I hadn\'t even applied', note: '"Solliciteren" = to apply for a job. "Niet eens" = not even. Makes the success extra impressive.' },
      { dutch: 'Doe normaal', english: 'Stop it / come off it / be normal', note: 'How Dutch people deflect compliments. NOT rude — it\'s modest. Literally "be normal" = don\'t overdo it.' },
      { dutch: 'Goed verdiend', english: 'Well deserved', note: 'Warm acknowledgement that someone earned their success. More meaningful than a casual "congrats".' },
      { dutch: 'Onwerkelijk', english: 'Unreal / surreal', note: 'When something feels too good or strange to be true. "Het voelt onwerkelijk" = it feels surreal.' },
      { dutch: 'Op je gerekend hebben', english: 'To have counted on someone / to have expected someone', note: '"Rekenen op" = to count on. "Ik had al op je gerekend" = I already knew you\'d be there.' },
      { dutch: 'Op jou!', english: 'To you! (toast)', note: 'A toast to someone. "Op jou!" = to you! "Op ons!" = to us! Short, warm, perfect for a celebration.' },
    ],
  },
  {
    id: 'ziek-thuis',
    title: 'Calling in Sick',
    dutchTitle: 'Ik bel me ziek',
    emoji: '🤒',
    description: 'That awkward Monday morning call',
    level: 'A2',
    context: 'Maandagochtend kwart voor negen. Mia heeft koorts en belt haar manager Kevin.',
    speakers: { A: 'Mia', B: 'Kevin' },
    lines: [
      { speaker: 'B', dutch: 'Kevin de Vries.', english: 'Kevin de Vries. (Dutch phone answer style)' },
      { speaker: 'A', dutch: 'Kevin, met Mia. Ik bel me ziek. Koorts en keelpijn.', english: 'Kevin, this is Mia. I\'m calling in sick. Fever and sore throat.' },
      { speaker: 'B', dutch: 'Oei. Dat klinkt niet goed. Griep?', english: 'Oh dear. That doesn\'t sound good. Flu?' },
      { speaker: 'A', dutch: 'Ik denk het wel. Ik voel me echt beroerd.', english: 'I think so. I really feel awful.' },
      { speaker: 'B', dutch: 'Dan moet je thuis blijven. Geen discussie.', english: 'Then you need to stay home. No discussion.' },
      { speaker: 'A', dutch: 'Maar de presentatie van donderdag...', english: 'But Thursday\'s presentation...' },
      { speaker: 'B', dutch: 'Mia. Thuis blijven.', english: 'Mia. Stay home.' },
      { speaker: 'A', dutch: 'Oké. Ik stuur Pieter even de bestanden.', english: 'Okay. I\'ll just send Pieter the files.' },
      { speaker: 'B', dutch: 'Dat hoeft niet meteen. Rust eerst uit. Gezondheid gaat voor.', english: 'You don\'t have to do that right now. Rest first. Health comes first.' },
      { speaker: 'A', dutch: 'Ik vind het vervelend voor het team.', english: 'I feel bad for the team.' },
      { speaker: 'B', dutch: 'We redden ons wel. Laat het weten hoe het morgen gaat.', english: 'We\'ll manage. Let me know how you\'re doing tomorrow.' },
      { speaker: 'A', dutch: 'Bedankt Kevin. Oh en... beterschap aan mezelf dan maar.', english: 'Thanks Kevin. Oh and... get well soon to myself then.' },
      { speaker: 'B', dutch: 'Haha. Beterschap Mia. Drink veel thee.', english: 'Haha. Get well soon Mia. Drink lots of tea.' },
    ],
    expressions: [
      { dutch: '[Naam]. (telefoon opnemen)', english: '[Name]. (answering the phone)', note: 'Dutch people answer with just their name. "Kevin de Vries." No "hello" first. Always their name.' },
      { dutch: 'Ik bel me ziek', english: 'I\'m calling in sick', note: 'The Dutch expression for calling in sick. "Zich ziek melden" is more formal. "Ik bel me ziek" = casual, direct.' },
      { dutch: 'Ik voel me beroerd', english: 'I feel awful / I feel terrible', note: '"Beroerd" = awful/rotten. "Ik voel me beroerd" is a strong but natural way to say you feel very ill.' },
      { dutch: 'Geen discussie', english: 'No discussion / not up for debate', note: 'Short, clear, final. Dutch directness at its best. When your manager says this, the decision is made.' },
      { dutch: 'Hoeft niet meteen', english: 'Doesn\'t have to be right now', note: '"Hoeven" = to need to (mainly in negatives and questions). "Dat hoeft niet" = you don\'t have to.' },
      { dutch: 'Gezondheid gaat voor', english: 'Health comes first', note: 'Dutch work culture genuinely values this. Rest, recover, then come back. Your manager means it.' },
      { dutch: 'We redden ons wel', english: 'We\'ll manage / we\'ll be fine', note: '"Zich redden" = to manage/cope. "We redden ons wel" = we\'ll figure it out. Reassuring and independent.' },
      { dutch: 'Beterschap', english: 'Get well soon', note: 'Always use "beterschap" when someone is sick. Never translate "get well soon" literally. One word. Done.' },
    ],
  },
  {
    id: 'huisgenoten-klusjes',
    title: 'Housemate Chores',
    dutchTitle: 'Wie doet wat?',
    emoji: '🧹',
    description: 'A tense negotiation in a Utrecht studenthouse',
    level: 'A2',
    context: 'Keuken, studentenhuis Utrecht. De vaat staat er al twee dagen in. Lena heeft het gezien. Thomas ook — maar deed alsof niet.',
    speakers: { A: 'Lena', B: 'Thomas' },
    lines: [
      { speaker: 'A', dutch: 'Thomas.', english: 'Thomas.' },
      { speaker: 'B', dutch: 'Hm?', english: 'Hm?' },
      { speaker: 'A', dutch: 'De keuken.', english: 'The kitchen.' },
      { speaker: 'B', dutch: 'Ik doe het straks, echt.', english: 'I\'ll do it later, really.' },
      { speaker: 'A', dutch: '"Straks" zei je gisteren ook al.', english: 'You already said "later" yesterday too.' },
      { speaker: 'B', dutch: 'Ik had het echt druk! Sorry. Ik doe het nu meteen.', english: 'I was genuinely busy! Sorry. I\'ll do it right now.' },
      { speaker: 'A', dutch: 'Goed. En de badkamer is ook aan de beurt trouwens.', english: 'Good. And the bathroom is also due, by the way.' },
      { speaker: 'B', dutch: 'Oké, keuken plus badkamer. Maar dan doe jij volgende week de gang?', english: 'Okay, kitchen plus bathroom. But then you do the hallway next week?' },
      { speaker: 'A', dutch: 'Ja, lijkt me eerlijk. Kunnen we ook een poetsrooster maken?', english: 'Yes, seems fair. Can we also make a cleaning schedule?' },
      { speaker: 'B', dutch: 'Dat stel je al voor sinds september.', english: 'You\'ve been suggesting that since September.' },
      { speaker: 'A', dutch: 'En jij zegt er steeds ja op maar doet het nooit.', english: 'And you keep saying yes to it but never do it.' },
      { speaker: 'B', dutch: 'Je hebt gelijk. Ik geef het toe. Vanavond Notion?', english: 'You\'re right. I admit it. Notion tonight?' },
      { speaker: 'A', dutch: 'Eindelijk. Ja. Na het eten.', english: 'Finally. Yes. After dinner.' },
    ],
    expressions: [
      { dutch: 'Straks', english: 'Later / in a bit', note: '"Straks" is wonderfully vague. It means soon-ish. In a studenthouse, "straks" can mean tomorrow. Everyone knows this.' },
      { dutch: 'Ik had het echt druk', english: 'I was genuinely busy', note: '"Druk hebben" = to be busy. "Echt druk" adds sincerity — or the attempt of it when avoiding chores.' },
      { dutch: 'Nu meteen', english: 'Right now / this instant', note: 'Stronger than just "nu". "Nu meteen" = no more delays, literally this second. Used when patience is gone.' },
      { dutch: 'Aan de beurt zijn', english: 'To be someone\'s turn', note: '"Wiens beurt is het?" = whose turn is it? Core vocabulary for shared living. Also used in queues and games.' },
      { dutch: 'Trouwens', english: 'By the way / also', note: 'Used to add a related point or a gentle heads-up. Like "oh, and by the way..."' },
      { dutch: 'Lijkt me eerlijk', english: 'Seems fair to me', note: '"Lijkt me" = seems to me. "Lijkt me eerlijk" = seems fair. A classic Dutch deal-closing phrase.' },
      { dutch: 'Steeds', english: 'Always / repeatedly / keep doing', note: '"Steeds" means something keeps happening. "Hij zegt steeds ja" = he keeps saying yes. Very useful.' },
      { dutch: 'Ik geef het toe', english: 'I admit it / I concede', note: 'Rare and valuable. When a Dutch housemate says this, write it down. It\'s a historic moment.' },
    ],
  },
  {
    id: 'fiets-gestolen',
    title: 'Stolen Bike',
    dutchTitle: 'Mijn fiets is weg!',
    emoji: '😤',
    description: 'Every Dutch person has lived this moment',
    level: 'A2',
    context: 'Nadia staat voor de fietsenrekken bij Amsterdam Centraal. Haar fiets is weg. Ze belt Bas.',
    speakers: { A: 'Nadia', B: 'Bas' },
    lines: [
      { speaker: 'A', dutch: 'Bas. Mijn fiets is weg.', english: 'Bas. My bike is gone.' },
      { speaker: 'B', dutch: 'Weg als in... gestolen?', english: 'Gone as in... stolen?' },
      { speaker: 'A', dutch: 'Goed slot en alles. Hij is er gewoon niet meer.', english: 'Good lock and everything. He\'s just not there anymore.' },
      { speaker: 'B', dutch: 'Hij. Je zegt "hij".', english: 'He. You said "he".' },
      { speaker: 'A', dutch: 'Ik had een band met die fiets, Bas.', english: 'I had a bond with that bike, Bas.' },
      { speaker: 'B', dutch: 'Oké. Heb je aangifte gedaan bij de politie?', english: 'Okay. Have you filed a report with the police?' },
      { speaker: 'A', dutch: 'Ja. Ze zeiden al dat de kans klein is. Typisch.', english: 'Yes. They already said the chances are small. Typical.' },
      { speaker: 'B', dutch: 'Wat zegt je verzekering?', english: 'What does your insurance say?' },
      { speaker: 'A', dutch: 'Die dekt het gelukkig. Maar ik moet nu lopend naar huis.', english: 'It covers it fortunately. But I have to walk home now.' },
      { speaker: 'B', dutch: 'Lopen?! In Amsterdam?! Doe je dat?', english: 'Walking?! In Amsterdam?! Are you actually doing that?' },
      { speaker: 'A', dutch: 'Wat moet ik anders? De tram is ook vertraagd.', english: 'What else am I supposed to do? The tram is delayed too.' },
      { speaker: 'B', dutch: 'Mijn reservefiets staat voor de deur. Kom maar.', english: 'My spare bike is at the front door. Come over.' },
      { speaker: 'A', dutch: 'Je bent een engel. En dit keer: drie sloten.', english: 'You\'re an angel. And this time: three locks.' },
      { speaker: 'B', dutch: 'Dat lijkt me inderdaad verstandig.', english: 'That does seem wise indeed.' },
    ],
    expressions: [
      { dutch: 'Weg als in...?', english: 'Gone as in...?', note: '"Als in" = as in. Used to ask someone to clarify what they mean. Very natural in shocked conversation.' },
      { dutch: 'En alles', english: 'And everything / the whole thing', note: '"Goed slot en alles" = good lock and everything. "En alles" adds emphasis — I did EVERYTHING right.' },
      { dutch: 'Een band hebben met', english: 'To have a bond with', note: '"Een band hebben met" = to feel connected to. Can be with people, pets, places — or apparently bikes.' },
      { dutch: 'Aangifte doen', english: 'To file a police report', note: 'You "do aangifte" at the politie. Bike theft is so common in NL that this is basically a standard life skill.' },
      { dutch: 'Typisch', english: 'Typical / of course (sarcastically)', note: '"Typisch!" when something predictably bad happens. Resigned, not angry. Like a slow nod of despair.' },
      { dutch: 'Wat moet ik anders?', english: 'What else am I supposed to do?', note: 'Expressing helplessness. "Wat moet ik anders?" = what choice do I have? Mild but effective.' },
      { dutch: 'Dat lijkt me verstandig', english: 'That seems wise / that sounds sensible', note: 'Calm, measured agreement. "Lijkt me verstandig" = I think that\'s a smart move. Very Dutch practicality.' },
      { dutch: 'Je bent een engel', english: 'You\'re an angel', note: 'Warm gratitude when someone saves you from a difficult situation. More heartfelt than a simple "bedankt".' },
    ],
  },
  {
    id: 'huurhuis-zoeken',
    title: 'Finding a Flat',
    dutchTitle: 'Een huis zoeken in Nederland',
    emoji: '🏠',
    description: 'The most relatable conversation for every expat in NL',
    level: 'B1',
    context: 'Na de vergadering. Ana (net verhuisd naar NL) en Sven (al drie jaar in Amsterdam).',
    speakers: { A: 'Ana', B: 'Sven' },
    lines: [
      { speaker: 'A', dutch: 'Sven, ik zoek al vier maanden naar een woning. Ik word er écht gek van.', english: 'Sven, I\'ve been looking for a home for four months. It\'s genuinely driving me crazy.' },
      { speaker: 'B', dutch: 'Vier maanden is hier niks. Ik deed er zeven over.', english: 'Four months is nothing here. It took me seven.' },
      { speaker: 'A', dutch: 'Zeven?!', english: 'Seven?!' },
      { speaker: 'B', dutch: 'Welkom in Amsterdam. Wat is je budget?', english: 'Welcome to Amsterdam. What\'s your budget?' },
      { speaker: 'A', dutch: 'Tot 1400. Maar voor dat geld krijg je hier bijna niks.', english: 'Up to 1400. But for that money you get almost nothing here.' },
      { speaker: 'B', dutch: 'Helaas klopt dat. Heb je ook buiten Amsterdam gekeken?', english: 'Unfortunately that\'s true. Have you also looked outside Amsterdam?' },
      { speaker: 'A', dutch: 'Ja, maar mijn werk is hier en ik heb nog geen fiets.', english: 'Yes, but my work is here and I don\'t have a bike yet.' },
      { speaker: 'B', dutch: 'Dat is het eerste wat je moet regelen. Een fiets. Dan wordt alles makkelijker.', english: 'That\'s the first thing you need to sort. A bike. Then everything gets easier.' },
      { speaker: 'A', dutch: 'En de sociale huurlijst?', english: 'And the social housing waiting list?' },
      { speaker: 'B', dutch: 'Tien jaar. Ik heb me ingeschreven, voor de grap.', english: 'Ten years. I registered, for laughs.' },
      { speaker: 'A', dutch: 'Dit is te waanzinnig voor woorden.', english: 'This is absolutely beyond belief.' },
      { speaker: 'B', dutch: 'Je went eraan. En vergeet niet: je hebt een BSN nodig voor alles hier.', english: 'You get used to it. And don\'t forget: you need a BSN number for everything here.' },
      { speaker: 'A', dutch: 'BSN, DigiD, OV-chipkaart... Nederland heeft veel nummers.', english: 'BSN, DigiD, OV-chipkaart... the Netherlands has a lot of numbers.' },
      { speaker: 'B', dutch: 'Welkom in het systeem. Ik hoor het als ik iets hoor.', english: 'Welcome to the system. I\'ll let you know if I hear anything.' },
    ],
    expressions: [
      { dutch: 'Ik word er gek van', english: 'It\'s driving me crazy', note: '"Ergens gek van worden" = to be driven insane by something. Very strong but very common frustration.' },
      { dutch: 'Voor dat geld krijg je niks', english: 'For that money you get nothing', note: 'A painfully accurate phrase for the Dutch housing market. "Voor X euro krijg je Y" = X buys you Y.' },
      { dutch: 'Helaas klopt dat', english: 'Unfortunately that\'s true', note: '"Kloppen" = to be correct. "Dat klopt" = that\'s right. "Helaas klopt dat" = sadly, you\'re correct.' },
      { dutch: 'Voor de grap', english: 'For laughs / as a joke / not seriously', note: 'Doing something without real hope. Registering for social housing in NL qualifies as doing it voor de grap.' },
      { dutch: 'Te waanzinnig voor woorden', english: 'Beyond words / absolutely insane', note: '"Te [adj] voor woorden" = too [adj] to even describe. The strongest Dutch expression of disbelief.' },
      { dutch: 'Je went eraan', english: 'You get used to it', note: '"Wennen aan" = to get used to. Said about Dutch weather, directness, housing costs, and cycling in rain.' },
      { dutch: 'Je hebt een BSN nodig voor alles', english: 'You need a BSN for everything', note: 'BSN = Burgerservicenummer, the Dutch equivalent of a national ID number. True — you need it for literally everything.' },
      { dutch: 'Ik hoor het als ik iets hoor', english: 'I\'ll let you know if I hear anything', note: 'Literally "I\'ll hear it when I hear something." The Dutch way to promise to pass on info. Warm and vague.' },
    ],
  },
]

export function getRealConversation(id: string): RealConversation | undefined {
  return realConversations.find((c) => c.id === id)
}

export function getRandomRealConversation(): RealConversation {
  return realConversations[Math.floor(Math.random() * realConversations.length)]
}
